// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entities.proto

package com.flipkart.vbroker.proto;

/**
 * Protobuf type {@code proto.ClusterMetadata}
 */
public final class ClusterMetadata extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.ClusterMetadata)
    ClusterMetadataOrBuilder {
    public static final int TOPICMETADATAS_FIELD_NUMBER = 1;
    public static final int NODES_FIELD_NUMBER = 2;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:proto.ClusterMetadata)
    private static final com.flipkart.vbroker.proto.ClusterMetadata DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<ClusterMetadata>
        PARSER = new com.google.protobuf.AbstractParser<ClusterMetadata>() {
        public ClusterMetadata parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new ClusterMetadata(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new com.flipkart.vbroker.proto.ClusterMetadata();
    }

    private java.util.List<com.flipkart.vbroker.proto.TopicMetadata> topicMetadatas_;
    private java.util.List<com.flipkart.vbroker.proto.Node> nodes_;
    private byte memoizedIsInitialized = -1;

    // Use ClusterMetadata.newBuilder() to construct.
    private ClusterMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private ClusterMetadata() {
        topicMetadatas_ = java.util.Collections.emptyList();
        nodes_ = java.util.Collections.emptyList();
    }

    private ClusterMetadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                            input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                            topicMetadatas_ = new java.util.ArrayList<com.flipkart.vbroker.proto.TopicMetadata>();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        topicMetadatas_.add(
                            input.readMessage(com.flipkart.vbroker.proto.TopicMetadata.parser(), extensionRegistry));
                        break;
                    }
                    case 18: {
                        if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                            nodes_ = new java.util.ArrayList<com.flipkart.vbroker.proto.Node>();
                            mutable_bitField0_ |= 0x00000002;
                        }
                        nodes_.add(
                            input.readMessage(com.flipkart.vbroker.proto.Node.parser(), extensionRegistry));
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                topicMetadatas_ = java.util.Collections.unmodifiableList(topicMetadatas_);
            }
            if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                nodes_ = java.util.Collections.unmodifiableList(nodes_);
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.flipkart.vbroker.proto.PEntities.internal_static_proto_ClusterMetadata_descriptor;
    }

    public static com.flipkart.vbroker.proto.ClusterMetadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.flipkart.vbroker.proto.ClusterMetadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.ClusterMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.flipkart.vbroker.proto.ClusterMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.ClusterMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.flipkart.vbroker.proto.ClusterMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.ClusterMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static com.flipkart.vbroker.proto.ClusterMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.ClusterMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.flipkart.vbroker.proto.ClusterMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.ClusterMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static com.flipkart.vbroker.proto.ClusterMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.flipkart.vbroker.proto.ClusterMetadata prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.flipkart.vbroker.proto.ClusterMetadata getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<ClusterMetadata> parser() {
        return PARSER;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.flipkart.vbroker.proto.PEntities.internal_static_proto_ClusterMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.flipkart.vbroker.proto.ClusterMetadata.class, com.flipkart.vbroker.proto.ClusterMetadata.Builder.class);
    }

    /**
     * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
     */
    public java.util.List<com.flipkart.vbroker.proto.TopicMetadata> getTopicMetadatasList() {
        return topicMetadatas_;
    }

    /**
     * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
     */
    public java.util.List<? extends com.flipkart.vbroker.proto.TopicMetadataOrBuilder>
    getTopicMetadatasOrBuilderList() {
        return topicMetadatas_;
    }

    /**
     * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
     */
    public int getTopicMetadatasCount() {
        return topicMetadatas_.size();
    }

    /**
     * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
     */
    public com.flipkart.vbroker.proto.TopicMetadata getTopicMetadatas(int index) {
        return topicMetadatas_.get(index);
    }

    /**
     * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
     */
    public com.flipkart.vbroker.proto.TopicMetadataOrBuilder getTopicMetadatasOrBuilder(
        int index) {
        return topicMetadatas_.get(index);
    }

    /**
     * <code>repeated .proto.Node nodes = 2;</code>
     */
    public java.util.List<com.flipkart.vbroker.proto.Node> getNodesList() {
        return nodes_;
    }

    /**
     * <code>repeated .proto.Node nodes = 2;</code>
     */
    public java.util.List<? extends com.flipkart.vbroker.proto.NodeOrBuilder>
    getNodesOrBuilderList() {
        return nodes_;
    }

    /**
     * <code>repeated .proto.Node nodes = 2;</code>
     */
    public int getNodesCount() {
        return nodes_.size();
    }

    /**
     * <code>repeated .proto.Node nodes = 2;</code>
     */
    public com.flipkart.vbroker.proto.Node getNodes(int index) {
        return nodes_.get(index);
    }

    /**
     * <code>repeated .proto.Node nodes = 2;</code>
     */
    public com.flipkart.vbroker.proto.NodeOrBuilder getNodesOrBuilder(
        int index) {
        return nodes_.get(index);
    }

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
        for (int i = 0; i < topicMetadatas_.size(); i++) {
            output.writeMessage(1, topicMetadatas_.get(i));
        }
        for (int i = 0; i < nodes_.size(); i++) {
            output.writeMessage(2, nodes_.get(i));
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < topicMetadatas_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(1, topicMetadatas_.get(i));
        }
        for (int i = 0; i < nodes_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(2, nodes_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.flipkart.vbroker.proto.ClusterMetadata)) {
            return super.equals(obj);
        }
        com.flipkart.vbroker.proto.ClusterMetadata other = (com.flipkart.vbroker.proto.ClusterMetadata) obj;

        boolean result = true;
        result = result && getTopicMetadatasList()
            .equals(other.getTopicMetadatasList());
        result = result && getNodesList()
            .equals(other.getNodesList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getTopicMetadatasCount() > 0) {
            hash = (37 * hash) + TOPICMETADATAS_FIELD_NUMBER;
            hash = (53 * hash) + getTopicMetadatasList().hashCode();
        }
        if (getNodesCount() > 0) {
            hash = (37 * hash) + NODES_FIELD_NUMBER;
            hash = (53 * hash) + getNodesList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClusterMetadata> getParserForType() {
        return PARSER;
    }

    public com.flipkart.vbroker.proto.ClusterMetadata getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code proto.ClusterMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ClusterMetadata)
        com.flipkart.vbroker.proto.ClusterMetadataOrBuilder {
        private int bitField0_;
        private java.util.List<com.flipkart.vbroker.proto.TopicMetadata> topicMetadatas_ =
            java.util.Collections.emptyList();
        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.flipkart.vbroker.proto.TopicMetadata, com.flipkart.vbroker.proto.TopicMetadata.Builder, com.flipkart.vbroker.proto.TopicMetadataOrBuilder> topicMetadatasBuilder_;
        private java.util.List<com.flipkart.vbroker.proto.Node> nodes_ =
            java.util.Collections.emptyList();
        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.flipkart.vbroker.proto.Node, com.flipkart.vbroker.proto.Node.Builder, com.flipkart.vbroker.proto.NodeOrBuilder> nodesBuilder_;

        // Construct using com.flipkart.vbroker.proto.ClusterMetadata.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.flipkart.vbroker.proto.PEntities.internal_static_proto_ClusterMetadata_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.flipkart.vbroker.proto.PEntities.internal_static_proto_ClusterMetadata_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.flipkart.vbroker.proto.ClusterMetadata.class, com.flipkart.vbroker.proto.ClusterMetadata.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
                getTopicMetadatasFieldBuilder();
                getNodesFieldBuilder();
            }
        }

        public Builder clear() {
            super.clear();
            if (topicMetadatasBuilder_ == null) {
                topicMetadatas_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
            } else {
                topicMetadatasBuilder_.clear();
            }
            if (nodesBuilder_ == null) {
                nodes_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
            } else {
                nodesBuilder_.clear();
            }
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.flipkart.vbroker.proto.PEntities.internal_static_proto_ClusterMetadata_descriptor;
        }

        public com.flipkart.vbroker.proto.ClusterMetadata getDefaultInstanceForType() {
            return com.flipkart.vbroker.proto.ClusterMetadata.getDefaultInstance();
        }

        public com.flipkart.vbroker.proto.ClusterMetadata build() {
            com.flipkart.vbroker.proto.ClusterMetadata result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public com.flipkart.vbroker.proto.ClusterMetadata buildPartial() {
            com.flipkart.vbroker.proto.ClusterMetadata result = new com.flipkart.vbroker.proto.ClusterMetadata(this);
            int from_bitField0_ = bitField0_;
            if (topicMetadatasBuilder_ == null) {
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    topicMetadatas_ = java.util.Collections.unmodifiableList(topicMetadatas_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.topicMetadatas_ = topicMetadatas_;
            } else {
                result.topicMetadatas_ = topicMetadatasBuilder_.build();
            }
            if (nodesBuilder_ == null) {
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    nodes_ = java.util.Collections.unmodifiableList(nodes_);
                    bitField0_ = (bitField0_ & ~0x00000002);
                }
                result.nodes_ = nodes_;
            } else {
                result.nodes_ = nodesBuilder_.build();
            }
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.flipkart.vbroker.proto.ClusterMetadata) {
                return mergeFrom((com.flipkart.vbroker.proto.ClusterMetadata) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.flipkart.vbroker.proto.ClusterMetadata other) {
            if (other == com.flipkart.vbroker.proto.ClusterMetadata.getDefaultInstance()) return this;
            if (topicMetadatasBuilder_ == null) {
                if (!other.topicMetadatas_.isEmpty()) {
                    if (topicMetadatas_.isEmpty()) {
                        topicMetadatas_ = other.topicMetadatas_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureTopicMetadatasIsMutable();
                        topicMetadatas_.addAll(other.topicMetadatas_);
                    }
                    onChanged();
                }
            } else {
                if (!other.topicMetadatas_.isEmpty()) {
                    if (topicMetadatasBuilder_.isEmpty()) {
                        topicMetadatasBuilder_.dispose();
                        topicMetadatasBuilder_ = null;
                        topicMetadatas_ = other.topicMetadatas_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                        topicMetadatasBuilder_ =
                            com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                getTopicMetadatasFieldBuilder() : null;
                    } else {
                        topicMetadatasBuilder_.addAllMessages(other.topicMetadatas_);
                    }
                }
            }
            if (nodesBuilder_ == null) {
                if (!other.nodes_.isEmpty()) {
                    if (nodes_.isEmpty()) {
                        nodes_ = other.nodes_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                    } else {
                        ensureNodesIsMutable();
                        nodes_.addAll(other.nodes_);
                    }
                    onChanged();
                }
            } else {
                if (!other.nodes_.isEmpty()) {
                    if (nodesBuilder_.isEmpty()) {
                        nodesBuilder_.dispose();
                        nodesBuilder_ = null;
                        nodes_ = other.nodes_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                        nodesBuilder_ =
                            com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                getNodesFieldBuilder() : null;
                    } else {
                        nodesBuilder_.addAllMessages(other.nodes_);
                    }
                }
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            com.flipkart.vbroker.proto.ClusterMetadata parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.flipkart.vbroker.proto.ClusterMetadata) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private void ensureTopicMetadatasIsMutable() {
            if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                topicMetadatas_ = new java.util.ArrayList<com.flipkart.vbroker.proto.TopicMetadata>(topicMetadatas_);
                bitField0_ |= 0x00000001;
            }
        }

        /**
         * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
         */
        public java.util.List<com.flipkart.vbroker.proto.TopicMetadata> getTopicMetadatasList() {
            if (topicMetadatasBuilder_ == null) {
                return java.util.Collections.unmodifiableList(topicMetadatas_);
            } else {
                return topicMetadatasBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
         */
        public int getTopicMetadatasCount() {
            if (topicMetadatasBuilder_ == null) {
                return topicMetadatas_.size();
            } else {
                return topicMetadatasBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
         */
        public com.flipkart.vbroker.proto.TopicMetadata getTopicMetadatas(int index) {
            if (topicMetadatasBuilder_ == null) {
                return topicMetadatas_.get(index);
            } else {
                return topicMetadatasBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
         */
        public Builder setTopicMetadatas(
            int index, com.flipkart.vbroker.proto.TopicMetadata value) {
            if (topicMetadatasBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureTopicMetadatasIsMutable();
                topicMetadatas_.set(index, value);
                onChanged();
            } else {
                topicMetadatasBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
         */
        public Builder setTopicMetadatas(
            int index, com.flipkart.vbroker.proto.TopicMetadata.Builder builderForValue) {
            if (topicMetadatasBuilder_ == null) {
                ensureTopicMetadatasIsMutable();
                topicMetadatas_.set(index, builderForValue.build());
                onChanged();
            } else {
                topicMetadatasBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
         */
        public Builder addTopicMetadatas(com.flipkart.vbroker.proto.TopicMetadata value) {
            if (topicMetadatasBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureTopicMetadatasIsMutable();
                topicMetadatas_.add(value);
                onChanged();
            } else {
                topicMetadatasBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
         */
        public Builder addTopicMetadatas(
            int index, com.flipkart.vbroker.proto.TopicMetadata value) {
            if (topicMetadatasBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureTopicMetadatasIsMutable();
                topicMetadatas_.add(index, value);
                onChanged();
            } else {
                topicMetadatasBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
         */
        public Builder addTopicMetadatas(
            com.flipkart.vbroker.proto.TopicMetadata.Builder builderForValue) {
            if (topicMetadatasBuilder_ == null) {
                ensureTopicMetadatasIsMutable();
                topicMetadatas_.add(builderForValue.build());
                onChanged();
            } else {
                topicMetadatasBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
         */
        public Builder addTopicMetadatas(
            int index, com.flipkart.vbroker.proto.TopicMetadata.Builder builderForValue) {
            if (topicMetadatasBuilder_ == null) {
                ensureTopicMetadatasIsMutable();
                topicMetadatas_.add(index, builderForValue.build());
                onChanged();
            } else {
                topicMetadatasBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
         */
        public Builder addAllTopicMetadatas(
            java.lang.Iterable<? extends com.flipkart.vbroker.proto.TopicMetadata> values) {
            if (topicMetadatasBuilder_ == null) {
                ensureTopicMetadatasIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                    values, topicMetadatas_);
                onChanged();
            } else {
                topicMetadatasBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
         */
        public Builder clearTopicMetadatas() {
            if (topicMetadatasBuilder_ == null) {
                topicMetadatas_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
            } else {
                topicMetadatasBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
         */
        public Builder removeTopicMetadatas(int index) {
            if (topicMetadatasBuilder_ == null) {
                ensureTopicMetadatasIsMutable();
                topicMetadatas_.remove(index);
                onChanged();
            } else {
                topicMetadatasBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
         */
        public com.flipkart.vbroker.proto.TopicMetadata.Builder getTopicMetadatasBuilder(
            int index) {
            return getTopicMetadatasFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
         */
        public com.flipkart.vbroker.proto.TopicMetadataOrBuilder getTopicMetadatasOrBuilder(
            int index) {
            if (topicMetadatasBuilder_ == null) {
                return topicMetadatas_.get(index);
            } else {
                return topicMetadatasBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
         */
        public java.util.List<? extends com.flipkart.vbroker.proto.TopicMetadataOrBuilder>
        getTopicMetadatasOrBuilderList() {
            if (topicMetadatasBuilder_ != null) {
                return topicMetadatasBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(topicMetadatas_);
            }
        }

        /**
         * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
         */
        public com.flipkart.vbroker.proto.TopicMetadata.Builder addTopicMetadatasBuilder() {
            return getTopicMetadatasFieldBuilder().addBuilder(
                com.flipkart.vbroker.proto.TopicMetadata.getDefaultInstance());
        }

        /**
         * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
         */
        public com.flipkart.vbroker.proto.TopicMetadata.Builder addTopicMetadatasBuilder(
            int index) {
            return getTopicMetadatasFieldBuilder().addBuilder(
                index, com.flipkart.vbroker.proto.TopicMetadata.getDefaultInstance());
        }

        /**
         * <code>repeated .proto.TopicMetadata topicMetadatas = 1;</code>
         */
        public java.util.List<com.flipkart.vbroker.proto.TopicMetadata.Builder>
        getTopicMetadatasBuilderList() {
            return getTopicMetadatasFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.flipkart.vbroker.proto.TopicMetadata, com.flipkart.vbroker.proto.TopicMetadata.Builder, com.flipkart.vbroker.proto.TopicMetadataOrBuilder>
        getTopicMetadatasFieldBuilder() {
            if (topicMetadatasBuilder_ == null) {
                topicMetadatasBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                    com.flipkart.vbroker.proto.TopicMetadata, com.flipkart.vbroker.proto.TopicMetadata.Builder, com.flipkart.vbroker.proto.TopicMetadataOrBuilder>(
                    topicMetadatas_,
                    ((bitField0_ & 0x00000001) == 0x00000001),
                    getParentForChildren(),
                    isClean());
                topicMetadatas_ = null;
            }
            return topicMetadatasBuilder_;
        }

        private void ensureNodesIsMutable() {
            if (!((bitField0_ & 0x00000002) == 0x00000002)) {
                nodes_ = new java.util.ArrayList<com.flipkart.vbroker.proto.Node>(nodes_);
                bitField0_ |= 0x00000002;
            }
        }

        /**
         * <code>repeated .proto.Node nodes = 2;</code>
         */
        public java.util.List<com.flipkart.vbroker.proto.Node> getNodesList() {
            if (nodesBuilder_ == null) {
                return java.util.Collections.unmodifiableList(nodes_);
            } else {
                return nodesBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .proto.Node nodes = 2;</code>
         */
        public int getNodesCount() {
            if (nodesBuilder_ == null) {
                return nodes_.size();
            } else {
                return nodesBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .proto.Node nodes = 2;</code>
         */
        public com.flipkart.vbroker.proto.Node getNodes(int index) {
            if (nodesBuilder_ == null) {
                return nodes_.get(index);
            } else {
                return nodesBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .proto.Node nodes = 2;</code>
         */
        public Builder setNodes(
            int index, com.flipkart.vbroker.proto.Node value) {
            if (nodesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureNodesIsMutable();
                nodes_.set(index, value);
                onChanged();
            } else {
                nodesBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .proto.Node nodes = 2;</code>
         */
        public Builder setNodes(
            int index, com.flipkart.vbroker.proto.Node.Builder builderForValue) {
            if (nodesBuilder_ == null) {
                ensureNodesIsMutable();
                nodes_.set(index, builderForValue.build());
                onChanged();
            } else {
                nodesBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .proto.Node nodes = 2;</code>
         */
        public Builder addNodes(com.flipkart.vbroker.proto.Node value) {
            if (nodesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureNodesIsMutable();
                nodes_.add(value);
                onChanged();
            } else {
                nodesBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .proto.Node nodes = 2;</code>
         */
        public Builder addNodes(
            int index, com.flipkart.vbroker.proto.Node value) {
            if (nodesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureNodesIsMutable();
                nodes_.add(index, value);
                onChanged();
            } else {
                nodesBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .proto.Node nodes = 2;</code>
         */
        public Builder addNodes(
            com.flipkart.vbroker.proto.Node.Builder builderForValue) {
            if (nodesBuilder_ == null) {
                ensureNodesIsMutable();
                nodes_.add(builderForValue.build());
                onChanged();
            } else {
                nodesBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .proto.Node nodes = 2;</code>
         */
        public Builder addNodes(
            int index, com.flipkart.vbroker.proto.Node.Builder builderForValue) {
            if (nodesBuilder_ == null) {
                ensureNodesIsMutable();
                nodes_.add(index, builderForValue.build());
                onChanged();
            } else {
                nodesBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .proto.Node nodes = 2;</code>
         */
        public Builder addAllNodes(
            java.lang.Iterable<? extends com.flipkart.vbroker.proto.Node> values) {
            if (nodesBuilder_ == null) {
                ensureNodesIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                    values, nodes_);
                onChanged();
            } else {
                nodesBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .proto.Node nodes = 2;</code>
         */
        public Builder clearNodes() {
            if (nodesBuilder_ == null) {
                nodes_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
            } else {
                nodesBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .proto.Node nodes = 2;</code>
         */
        public Builder removeNodes(int index) {
            if (nodesBuilder_ == null) {
                ensureNodesIsMutable();
                nodes_.remove(index);
                onChanged();
            } else {
                nodesBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .proto.Node nodes = 2;</code>
         */
        public com.flipkart.vbroker.proto.Node.Builder getNodesBuilder(
            int index) {
            return getNodesFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .proto.Node nodes = 2;</code>
         */
        public com.flipkart.vbroker.proto.NodeOrBuilder getNodesOrBuilder(
            int index) {
            if (nodesBuilder_ == null) {
                return nodes_.get(index);
            } else {
                return nodesBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .proto.Node nodes = 2;</code>
         */
        public java.util.List<? extends com.flipkart.vbroker.proto.NodeOrBuilder>
        getNodesOrBuilderList() {
            if (nodesBuilder_ != null) {
                return nodesBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(nodes_);
            }
        }

        /**
         * <code>repeated .proto.Node nodes = 2;</code>
         */
        public com.flipkart.vbroker.proto.Node.Builder addNodesBuilder() {
            return getNodesFieldBuilder().addBuilder(
                com.flipkart.vbroker.proto.Node.getDefaultInstance());
        }

        /**
         * <code>repeated .proto.Node nodes = 2;</code>
         */
        public com.flipkart.vbroker.proto.Node.Builder addNodesBuilder(
            int index) {
            return getNodesFieldBuilder().addBuilder(
                index, com.flipkart.vbroker.proto.Node.getDefaultInstance());
        }

        /**
         * <code>repeated .proto.Node nodes = 2;</code>
         */
        public java.util.List<com.flipkart.vbroker.proto.Node.Builder>
        getNodesBuilderList() {
            return getNodesFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.flipkart.vbroker.proto.Node, com.flipkart.vbroker.proto.Node.Builder, com.flipkart.vbroker.proto.NodeOrBuilder>
        getNodesFieldBuilder() {
            if (nodesBuilder_ == null) {
                nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                    com.flipkart.vbroker.proto.Node, com.flipkart.vbroker.proto.Node.Builder, com.flipkart.vbroker.proto.NodeOrBuilder>(
                    nodes_,
                    ((bitField0_ & 0x00000002) == 0x00000002),
                    getParentForChildren(),
                    isClean());
                nodes_ = null;
            }
            return nodesBuilder_;
        }

        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:proto.ClusterMetadata)
    }

}

