// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: responses.proto

package com.flipkart.vbroker.proto;

public interface CreateTopicsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CreateTopicsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.CreateTopicResponse createTopicsResponse = 1;</code>
   */
  java.util.List<com.flipkart.vbroker.proto.CreateTopicResponse> 
      getCreateTopicsResponseList();
  /**
   * <code>repeated .proto.CreateTopicResponse createTopicsResponse = 1;</code>
   */
  com.flipkart.vbroker.proto.CreateTopicResponse getCreateTopicsResponse(int index);
  /**
   * <code>repeated .proto.CreateTopicResponse createTopicsResponse = 1;</code>
   */
  int getCreateTopicsResponseCount();
  /**
   * <code>repeated .proto.CreateTopicResponse createTopicsResponse = 1;</code>
   */
  java.util.List<? extends com.flipkart.vbroker.proto.CreateTopicResponseOrBuilder> 
      getCreateTopicsResponseOrBuilderList();
  /**
   * <code>repeated .proto.CreateTopicResponse createTopicsResponse = 1;</code>
   */
  com.flipkart.vbroker.proto.CreateTopicResponseOrBuilder getCreateTopicsResponseOrBuilder(
      int index);
}
