// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests.proto

package com.flipkart.vbroker.proto;

/**
 * <pre>
 * create topics request
 * </pre>
 * <p>
 * Protobuf type {@code proto.CreateTopicsRequest}
 */
public final class CreateTopicsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.CreateTopicsRequest)
    CreateTopicsRequestOrBuilder {
    public static final int TOPICS_FIELD_NUMBER = 1;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:proto.CreateTopicsRequest)
    private static final com.flipkart.vbroker.proto.CreateTopicsRequest DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<CreateTopicsRequest>
        PARSER = new com.google.protobuf.AbstractParser<CreateTopicsRequest>() {
        public CreateTopicsRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new CreateTopicsRequest(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new com.flipkart.vbroker.proto.CreateTopicsRequest();
    }

    private java.util.List<com.flipkart.vbroker.proto.ProtoTopic> topics_;
    private byte memoizedIsInitialized = -1;

    // Use CreateTopicsRequest.newBuilder() to construct.
    private CreateTopicsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private CreateTopicsRequest() {
        topics_ = java.util.Collections.emptyList();
    }

    private CreateTopicsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                            input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                            topics_ = new java.util.ArrayList<com.flipkart.vbroker.proto.ProtoTopic>();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        topics_.add(
                            input.readMessage(com.flipkart.vbroker.proto.ProtoTopic.parser(), extensionRegistry));
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                topics_ = java.util.Collections.unmodifiableList(topics_);
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.flipkart.vbroker.proto.PRequests.internal_static_proto_CreateTopicsRequest_descriptor;
    }

    public static com.flipkart.vbroker.proto.CreateTopicsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.flipkart.vbroker.proto.CreateTopicsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.CreateTopicsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.flipkart.vbroker.proto.CreateTopicsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.CreateTopicsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.flipkart.vbroker.proto.CreateTopicsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.CreateTopicsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static com.flipkart.vbroker.proto.CreateTopicsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.CreateTopicsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.flipkart.vbroker.proto.CreateTopicsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.CreateTopicsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static com.flipkart.vbroker.proto.CreateTopicsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.flipkart.vbroker.proto.CreateTopicsRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.flipkart.vbroker.proto.CreateTopicsRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<CreateTopicsRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.flipkart.vbroker.proto.PRequests.internal_static_proto_CreateTopicsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.flipkart.vbroker.proto.CreateTopicsRequest.class, com.flipkart.vbroker.proto.CreateTopicsRequest.Builder.class);
    }

    /**
     * <code>repeated .proto.ProtoTopic topics = 1;</code>
     */
    public java.util.List<com.flipkart.vbroker.proto.ProtoTopic> getTopicsList() {
        return topics_;
    }

    /**
     * <code>repeated .proto.ProtoTopic topics = 1;</code>
     */
    public java.util.List<? extends com.flipkart.vbroker.proto.ProtoTopicOrBuilder>
    getTopicsOrBuilderList() {
        return topics_;
    }

    /**
     * <code>repeated .proto.ProtoTopic topics = 1;</code>
     */
    public int getTopicsCount() {
        return topics_.size();
    }

    /**
     * <code>repeated .proto.ProtoTopic topics = 1;</code>
     */
    public com.flipkart.vbroker.proto.ProtoTopic getTopics(int index) {
        return topics_.get(index);
    }

    /**
     * <code>repeated .proto.ProtoTopic topics = 1;</code>
     */
    public com.flipkart.vbroker.proto.ProtoTopicOrBuilder getTopicsOrBuilder(
        int index) {
        return topics_.get(index);
    }

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
        for (int i = 0; i < topics_.size(); i++) {
            output.writeMessage(1, topics_.get(i));
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < topics_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(1, topics_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.flipkart.vbroker.proto.CreateTopicsRequest)) {
            return super.equals(obj);
        }
        com.flipkart.vbroker.proto.CreateTopicsRequest other = (com.flipkart.vbroker.proto.CreateTopicsRequest) obj;

        boolean result = true;
        result = result && getTopicsList()
            .equals(other.getTopicsList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getTopicsCount() > 0) {
            hash = (37 * hash) + TOPICS_FIELD_NUMBER;
            hash = (53 * hash) + getTopicsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateTopicsRequest> getParserForType() {
        return PARSER;
    }

    public com.flipkart.vbroker.proto.CreateTopicsRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * <pre>
     * create topics request
     * </pre>
     * <p>
     * Protobuf type {@code proto.CreateTopicsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.CreateTopicsRequest)
        com.flipkart.vbroker.proto.CreateTopicsRequestOrBuilder {
        private int bitField0_;
        private java.util.List<com.flipkart.vbroker.proto.ProtoTopic> topics_ =
            java.util.Collections.emptyList();
        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.flipkart.vbroker.proto.ProtoTopic, com.flipkart.vbroker.proto.ProtoTopic.Builder, com.flipkart.vbroker.proto.ProtoTopicOrBuilder> topicsBuilder_;

        // Construct using com.flipkart.vbroker.proto.CreateTopicsRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.flipkart.vbroker.proto.PRequests.internal_static_proto_CreateTopicsRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.flipkart.vbroker.proto.PRequests.internal_static_proto_CreateTopicsRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.flipkart.vbroker.proto.CreateTopicsRequest.class, com.flipkart.vbroker.proto.CreateTopicsRequest.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
                getTopicsFieldBuilder();
            }
        }

        public Builder clear() {
            super.clear();
            if (topicsBuilder_ == null) {
                topics_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
            } else {
                topicsBuilder_.clear();
            }
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.flipkart.vbroker.proto.PRequests.internal_static_proto_CreateTopicsRequest_descriptor;
        }

        public com.flipkart.vbroker.proto.CreateTopicsRequest getDefaultInstanceForType() {
            return com.flipkart.vbroker.proto.CreateTopicsRequest.getDefaultInstance();
        }

        public com.flipkart.vbroker.proto.CreateTopicsRequest build() {
            com.flipkart.vbroker.proto.CreateTopicsRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public com.flipkart.vbroker.proto.CreateTopicsRequest buildPartial() {
            com.flipkart.vbroker.proto.CreateTopicsRequest result = new com.flipkart.vbroker.proto.CreateTopicsRequest(this);
            int from_bitField0_ = bitField0_;
            if (topicsBuilder_ == null) {
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    topics_ = java.util.Collections.unmodifiableList(topics_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.topics_ = topics_;
            } else {
                result.topics_ = topicsBuilder_.build();
            }
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.flipkart.vbroker.proto.CreateTopicsRequest) {
                return mergeFrom((com.flipkart.vbroker.proto.CreateTopicsRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.flipkart.vbroker.proto.CreateTopicsRequest other) {
            if (other == com.flipkart.vbroker.proto.CreateTopicsRequest.getDefaultInstance()) return this;
            if (topicsBuilder_ == null) {
                if (!other.topics_.isEmpty()) {
                    if (topics_.isEmpty()) {
                        topics_ = other.topics_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureTopicsIsMutable();
                        topics_.addAll(other.topics_);
                    }
                    onChanged();
                }
            } else {
                if (!other.topics_.isEmpty()) {
                    if (topicsBuilder_.isEmpty()) {
                        topicsBuilder_.dispose();
                        topicsBuilder_ = null;
                        topics_ = other.topics_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                        topicsBuilder_ =
                            com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                getTopicsFieldBuilder() : null;
                    } else {
                        topicsBuilder_.addAllMessages(other.topics_);
                    }
                }
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            com.flipkart.vbroker.proto.CreateTopicsRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.flipkart.vbroker.proto.CreateTopicsRequest) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private void ensureTopicsIsMutable() {
            if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                topics_ = new java.util.ArrayList<com.flipkart.vbroker.proto.ProtoTopic>(topics_);
                bitField0_ |= 0x00000001;
            }
        }

        /**
         * <code>repeated .proto.ProtoTopic topics = 1;</code>
         */
        public java.util.List<com.flipkart.vbroker.proto.ProtoTopic> getTopicsList() {
            if (topicsBuilder_ == null) {
                return java.util.Collections.unmodifiableList(topics_);
            } else {
                return topicsBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .proto.ProtoTopic topics = 1;</code>
         */
        public int getTopicsCount() {
            if (topicsBuilder_ == null) {
                return topics_.size();
            } else {
                return topicsBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .proto.ProtoTopic topics = 1;</code>
         */
        public com.flipkart.vbroker.proto.ProtoTopic getTopics(int index) {
            if (topicsBuilder_ == null) {
                return topics_.get(index);
            } else {
                return topicsBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .proto.ProtoTopic topics = 1;</code>
         */
        public Builder setTopics(
            int index, com.flipkart.vbroker.proto.ProtoTopic value) {
            if (topicsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureTopicsIsMutable();
                topics_.set(index, value);
                onChanged();
            } else {
                topicsBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .proto.ProtoTopic topics = 1;</code>
         */
        public Builder setTopics(
            int index, com.flipkart.vbroker.proto.ProtoTopic.Builder builderForValue) {
            if (topicsBuilder_ == null) {
                ensureTopicsIsMutable();
                topics_.set(index, builderForValue.build());
                onChanged();
            } else {
                topicsBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .proto.ProtoTopic topics = 1;</code>
         */
        public Builder addTopics(com.flipkart.vbroker.proto.ProtoTopic value) {
            if (topicsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureTopicsIsMutable();
                topics_.add(value);
                onChanged();
            } else {
                topicsBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .proto.ProtoTopic topics = 1;</code>
         */
        public Builder addTopics(
            int index, com.flipkart.vbroker.proto.ProtoTopic value) {
            if (topicsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureTopicsIsMutable();
                topics_.add(index, value);
                onChanged();
            } else {
                topicsBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .proto.ProtoTopic topics = 1;</code>
         */
        public Builder addTopics(
            com.flipkart.vbroker.proto.ProtoTopic.Builder builderForValue) {
            if (topicsBuilder_ == null) {
                ensureTopicsIsMutable();
                topics_.add(builderForValue.build());
                onChanged();
            } else {
                topicsBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .proto.ProtoTopic topics = 1;</code>
         */
        public Builder addTopics(
            int index, com.flipkart.vbroker.proto.ProtoTopic.Builder builderForValue) {
            if (topicsBuilder_ == null) {
                ensureTopicsIsMutable();
                topics_.add(index, builderForValue.build());
                onChanged();
            } else {
                topicsBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .proto.ProtoTopic topics = 1;</code>
         */
        public Builder addAllTopics(
            java.lang.Iterable<? extends com.flipkart.vbroker.proto.ProtoTopic> values) {
            if (topicsBuilder_ == null) {
                ensureTopicsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                    values, topics_);
                onChanged();
            } else {
                topicsBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .proto.ProtoTopic topics = 1;</code>
         */
        public Builder clearTopics() {
            if (topicsBuilder_ == null) {
                topics_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
            } else {
                topicsBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .proto.ProtoTopic topics = 1;</code>
         */
        public Builder removeTopics(int index) {
            if (topicsBuilder_ == null) {
                ensureTopicsIsMutable();
                topics_.remove(index);
                onChanged();
            } else {
                topicsBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .proto.ProtoTopic topics = 1;</code>
         */
        public com.flipkart.vbroker.proto.ProtoTopic.Builder getTopicsBuilder(
            int index) {
            return getTopicsFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .proto.ProtoTopic topics = 1;</code>
         */
        public com.flipkart.vbroker.proto.ProtoTopicOrBuilder getTopicsOrBuilder(
            int index) {
            if (topicsBuilder_ == null) {
                return topics_.get(index);
            } else {
                return topicsBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .proto.ProtoTopic topics = 1;</code>
         */
        public java.util.List<? extends com.flipkart.vbroker.proto.ProtoTopicOrBuilder>
        getTopicsOrBuilderList() {
            if (topicsBuilder_ != null) {
                return topicsBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(topics_);
            }
        }

        /**
         * <code>repeated .proto.ProtoTopic topics = 1;</code>
         */
        public com.flipkart.vbroker.proto.ProtoTopic.Builder addTopicsBuilder() {
            return getTopicsFieldBuilder().addBuilder(
                com.flipkart.vbroker.proto.ProtoTopic.getDefaultInstance());
        }

        /**
         * <code>repeated .proto.ProtoTopic topics = 1;</code>
         */
        public com.flipkart.vbroker.proto.ProtoTopic.Builder addTopicsBuilder(
            int index) {
            return getTopicsFieldBuilder().addBuilder(
                index, com.flipkart.vbroker.proto.ProtoTopic.getDefaultInstance());
        }

        /**
         * <code>repeated .proto.ProtoTopic topics = 1;</code>
         */
        public java.util.List<com.flipkart.vbroker.proto.ProtoTopic.Builder>
        getTopicsBuilderList() {
            return getTopicsFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.flipkart.vbroker.proto.ProtoTopic, com.flipkart.vbroker.proto.ProtoTopic.Builder, com.flipkart.vbroker.proto.ProtoTopicOrBuilder>
        getTopicsFieldBuilder() {
            if (topicsBuilder_ == null) {
                topicsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                    com.flipkart.vbroker.proto.ProtoTopic, com.flipkart.vbroker.proto.ProtoTopic.Builder, com.flipkart.vbroker.proto.ProtoTopicOrBuilder>(
                    topics_,
                    ((bitField0_ & 0x00000001) == 0x00000001),
                    getParentForChildren(),
                    isClean());
                topics_ = null;
            }
            return topicsBuilder_;
        }

        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:proto.CreateTopicsRequest)
    }

}

