// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests.proto

package com.flipkart.vbroker.proto;

public interface GetAllTopicsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetAllTopicsRequest)
    com.google.protobuf.MessageOrBuilder {
}
