// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: responses.proto

package com.flipkart.vbroker.proto;

/**
 * Protobuf type {@code proto.GetLagsResponse}
 */
public  final class GetLagsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.GetLagsResponse)
    GetLagsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetLagsResponse.newBuilder() to construct.
  private GetLagsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetLagsResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetLagsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.flipkart.vbroker.proto.SubscriptionLag.Builder subBuilder = null;
            if (subscriptionLags_ != null) {
              subBuilder = subscriptionLags_.toBuilder();
            }
            subscriptionLags_ = input.readMessage(com.flipkart.vbroker.proto.SubscriptionLag.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(subscriptionLags_);
              subscriptionLags_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.flipkart.vbroker.proto.PResponses.internal_static_proto_GetLagsResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.flipkart.vbroker.proto.PResponses.internal_static_proto_GetLagsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.flipkart.vbroker.proto.GetLagsResponse.class, com.flipkart.vbroker.proto.GetLagsResponse.Builder.class);
  }

  public static final int SUBSCRIPTIONLAGS_FIELD_NUMBER = 1;
  private com.flipkart.vbroker.proto.SubscriptionLag subscriptionLags_;
  /**
   * <code>.proto.SubscriptionLag subscriptionLags = 1;</code>
   */
  public boolean hasSubscriptionLags() {
    return subscriptionLags_ != null;
  }
  /**
   * <code>.proto.SubscriptionLag subscriptionLags = 1;</code>
   */
  public com.flipkart.vbroker.proto.SubscriptionLag getSubscriptionLags() {
    return subscriptionLags_ == null ? com.flipkart.vbroker.proto.SubscriptionLag.getDefaultInstance() : subscriptionLags_;
  }
  /**
   * <code>.proto.SubscriptionLag subscriptionLags = 1;</code>
   */
  public com.flipkart.vbroker.proto.SubscriptionLagOrBuilder getSubscriptionLagsOrBuilder() {
    return getSubscriptionLags();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (subscriptionLags_ != null) {
      output.writeMessage(1, getSubscriptionLags());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (subscriptionLags_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSubscriptionLags());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.flipkart.vbroker.proto.GetLagsResponse)) {
      return super.equals(obj);
    }
    com.flipkart.vbroker.proto.GetLagsResponse other = (com.flipkart.vbroker.proto.GetLagsResponse) obj;

    boolean result = true;
    result = result && (hasSubscriptionLags() == other.hasSubscriptionLags());
    if (hasSubscriptionLags()) {
      result = result && getSubscriptionLags()
          .equals(other.getSubscriptionLags());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSubscriptionLags()) {
      hash = (37 * hash) + SUBSCRIPTIONLAGS_FIELD_NUMBER;
      hash = (53 * hash) + getSubscriptionLags().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.flipkart.vbroker.proto.GetLagsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.flipkart.vbroker.proto.GetLagsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.flipkart.vbroker.proto.GetLagsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.flipkart.vbroker.proto.GetLagsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.flipkart.vbroker.proto.GetLagsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.flipkart.vbroker.proto.GetLagsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.flipkart.vbroker.proto.GetLagsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.flipkart.vbroker.proto.GetLagsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.flipkart.vbroker.proto.GetLagsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.flipkart.vbroker.proto.GetLagsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.flipkart.vbroker.proto.GetLagsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.flipkart.vbroker.proto.GetLagsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.flipkart.vbroker.proto.GetLagsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.GetLagsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.GetLagsResponse)
      com.flipkart.vbroker.proto.GetLagsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.flipkart.vbroker.proto.PResponses.internal_static_proto_GetLagsResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.flipkart.vbroker.proto.PResponses.internal_static_proto_GetLagsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.flipkart.vbroker.proto.GetLagsResponse.class, com.flipkart.vbroker.proto.GetLagsResponse.Builder.class);
    }

    // Construct using com.flipkart.vbroker.proto.GetLagsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (subscriptionLagsBuilder_ == null) {
        subscriptionLags_ = null;
      } else {
        subscriptionLags_ = null;
        subscriptionLagsBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.flipkart.vbroker.proto.PResponses.internal_static_proto_GetLagsResponse_descriptor;
    }

    public com.flipkart.vbroker.proto.GetLagsResponse getDefaultInstanceForType() {
      return com.flipkart.vbroker.proto.GetLagsResponse.getDefaultInstance();
    }

    public com.flipkart.vbroker.proto.GetLagsResponse build() {
      com.flipkart.vbroker.proto.GetLagsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.flipkart.vbroker.proto.GetLagsResponse buildPartial() {
      com.flipkart.vbroker.proto.GetLagsResponse result = new com.flipkart.vbroker.proto.GetLagsResponse(this);
      if (subscriptionLagsBuilder_ == null) {
        result.subscriptionLags_ = subscriptionLags_;
      } else {
        result.subscriptionLags_ = subscriptionLagsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.flipkart.vbroker.proto.GetLagsResponse) {
        return mergeFrom((com.flipkart.vbroker.proto.GetLagsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.flipkart.vbroker.proto.GetLagsResponse other) {
      if (other == com.flipkart.vbroker.proto.GetLagsResponse.getDefaultInstance()) return this;
      if (other.hasSubscriptionLags()) {
        mergeSubscriptionLags(other.getSubscriptionLags());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.flipkart.vbroker.proto.GetLagsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.flipkart.vbroker.proto.GetLagsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.flipkart.vbroker.proto.SubscriptionLag subscriptionLags_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.flipkart.vbroker.proto.SubscriptionLag, com.flipkart.vbroker.proto.SubscriptionLag.Builder, com.flipkart.vbroker.proto.SubscriptionLagOrBuilder> subscriptionLagsBuilder_;
    /**
     * <code>.proto.SubscriptionLag subscriptionLags = 1;</code>
     */
    public boolean hasSubscriptionLags() {
      return subscriptionLagsBuilder_ != null || subscriptionLags_ != null;
    }
    /**
     * <code>.proto.SubscriptionLag subscriptionLags = 1;</code>
     */
    public com.flipkart.vbroker.proto.SubscriptionLag getSubscriptionLags() {
      if (subscriptionLagsBuilder_ == null) {
        return subscriptionLags_ == null ? com.flipkart.vbroker.proto.SubscriptionLag.getDefaultInstance() : subscriptionLags_;
      } else {
        return subscriptionLagsBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.SubscriptionLag subscriptionLags = 1;</code>
     */
    public Builder setSubscriptionLags(com.flipkart.vbroker.proto.SubscriptionLag value) {
      if (subscriptionLagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        subscriptionLags_ = value;
        onChanged();
      } else {
        subscriptionLagsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.SubscriptionLag subscriptionLags = 1;</code>
     */
    public Builder setSubscriptionLags(
        com.flipkart.vbroker.proto.SubscriptionLag.Builder builderForValue) {
      if (subscriptionLagsBuilder_ == null) {
        subscriptionLags_ = builderForValue.build();
        onChanged();
      } else {
        subscriptionLagsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.SubscriptionLag subscriptionLags = 1;</code>
     */
    public Builder mergeSubscriptionLags(com.flipkart.vbroker.proto.SubscriptionLag value) {
      if (subscriptionLagsBuilder_ == null) {
        if (subscriptionLags_ != null) {
          subscriptionLags_ =
            com.flipkart.vbroker.proto.SubscriptionLag.newBuilder(subscriptionLags_).mergeFrom(value).buildPartial();
        } else {
          subscriptionLags_ = value;
        }
        onChanged();
      } else {
        subscriptionLagsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.SubscriptionLag subscriptionLags = 1;</code>
     */
    public Builder clearSubscriptionLags() {
      if (subscriptionLagsBuilder_ == null) {
        subscriptionLags_ = null;
        onChanged();
      } else {
        subscriptionLags_ = null;
        subscriptionLagsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.SubscriptionLag subscriptionLags = 1;</code>
     */
    public com.flipkart.vbroker.proto.SubscriptionLag.Builder getSubscriptionLagsBuilder() {
      
      onChanged();
      return getSubscriptionLagsFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.SubscriptionLag subscriptionLags = 1;</code>
     */
    public com.flipkart.vbroker.proto.SubscriptionLagOrBuilder getSubscriptionLagsOrBuilder() {
      if (subscriptionLagsBuilder_ != null) {
        return subscriptionLagsBuilder_.getMessageOrBuilder();
      } else {
        return subscriptionLags_ == null ?
            com.flipkart.vbroker.proto.SubscriptionLag.getDefaultInstance() : subscriptionLags_;
      }
    }
    /**
     * <code>.proto.SubscriptionLag subscriptionLags = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.flipkart.vbroker.proto.SubscriptionLag, com.flipkart.vbroker.proto.SubscriptionLag.Builder, com.flipkart.vbroker.proto.SubscriptionLagOrBuilder> 
        getSubscriptionLagsFieldBuilder() {
      if (subscriptionLagsBuilder_ == null) {
        subscriptionLagsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.flipkart.vbroker.proto.SubscriptionLag, com.flipkart.vbroker.proto.SubscriptionLag.Builder, com.flipkart.vbroker.proto.SubscriptionLagOrBuilder>(
                getSubscriptionLags(),
                getParentForChildren(),
                isClean());
        subscriptionLags_ = null;
      }
      return subscriptionLagsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.GetLagsResponse)
  }

  // @@protoc_insertion_point(class_scope:proto.GetLagsResponse)
  private static final com.flipkart.vbroker.proto.GetLagsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.flipkart.vbroker.proto.GetLagsResponse();
  }

  public static com.flipkart.vbroker.proto.GetLagsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetLagsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetLagsResponse>() {
    public GetLagsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetLagsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetLagsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetLagsResponse> getParserForType() {
    return PARSER;
  }

  public com.flipkart.vbroker.proto.GetLagsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

