// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests.proto

package com.flipkart.vbroker.proto;

/**
 * <pre>
 * get offset
 * </pre>
 * <p>
 * Protobuf type {@code proto.GetPartSubscriptionOffsetsRequest}
 */
public final class GetPartSubscriptionOffsetsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.GetPartSubscriptionOffsetsRequest)
    GetPartSubscriptionOffsetsRequestOrBuilder {
    public static final int PARTITIONID_FIELD_NUMBER = 1;
    public static final int GROUPIDS_FIELD_NUMBER = 2;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:proto.GetPartSubscriptionOffsetsRequest)
    private static final com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<GetPartSubscriptionOffsetsRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetPartSubscriptionOffsetsRequest>() {
        public GetPartSubscriptionOffsetsRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new GetPartSubscriptionOffsetsRequest(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest();
    }

    private int bitField0_;
    private int partitionId_;
    private com.google.protobuf.LazyStringList groupIds_;
    private byte memoizedIsInitialized = -1;

    // Use GetPartSubscriptionOffsetsRequest.newBuilder() to construct.
    private GetPartSubscriptionOffsetsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private GetPartSubscriptionOffsetsRequest() {
        partitionId_ = 0;
        groupIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private GetPartSubscriptionOffsetsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                            input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        partitionId_ = input.readInt32();
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();
                        if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                            groupIds_ = new com.google.protobuf.LazyStringArrayList();
                            mutable_bitField0_ |= 0x00000002;
                        }
                        groupIds_.add(s);
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                groupIds_ = groupIds_.getUnmodifiableView();
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.flipkart.vbroker.proto.PRequests.internal_static_proto_GetPartSubscriptionOffsetsRequest_descriptor;
    }

    public static com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<GetPartSubscriptionOffsetsRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.flipkart.vbroker.proto.PRequests.internal_static_proto_GetPartSubscriptionOffsetsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest.class, com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest.Builder.class);
    }

    /**
     * <code>int32 partitionId = 1;</code>
     */
    public int getPartitionId() {
        return partitionId_;
    }

    /**
     * <code>repeated string groupIds = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
    getGroupIdsList() {
        return groupIds_;
    }

    /**
     * <code>repeated string groupIds = 2;</code>
     */
    public int getGroupIdsCount() {
        return groupIds_.size();
    }

    /**
     * <code>repeated string groupIds = 2;</code>
     */
    public java.lang.String getGroupIds(int index) {
        return groupIds_.get(index);
    }

    /**
     * <code>repeated string groupIds = 2;</code>
     */
    public com.google.protobuf.ByteString
    getGroupIdsBytes(int index) {
        return groupIds_.getByteString(index);
    }

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
        if (partitionId_ != 0) {
            output.writeInt32(1, partitionId_);
        }
        for (int i = 0; i < groupIds_.size(); i++) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, groupIds_.getRaw(i));
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (partitionId_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(1, partitionId_);
        }
        {
            int dataSize = 0;
            for (int i = 0; i < groupIds_.size(); i++) {
                dataSize += computeStringSizeNoTag(groupIds_.getRaw(i));
            }
            size += dataSize;
            size += 1 * getGroupIdsList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest)) {
            return super.equals(obj);
        }
        com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest other = (com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest) obj;

        boolean result = true;
        result = result && (getPartitionId()
            == other.getPartitionId());
        result = result && getGroupIdsList()
            .equals(other.getGroupIdsList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + PARTITIONID_FIELD_NUMBER;
        hash = (53 * hash) + getPartitionId();
        if (getGroupIdsCount() > 0) {
            hash = (37 * hash) + GROUPIDS_FIELD_NUMBER;
            hash = (53 * hash) + getGroupIdsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetPartSubscriptionOffsetsRequest> getParserForType() {
        return PARSER;
    }

    public com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * <pre>
     * get offset
     * </pre>
     * <p>
     * Protobuf type {@code proto.GetPartSubscriptionOffsetsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.GetPartSubscriptionOffsetsRequest)
        com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequestOrBuilder {
        private int bitField0_;
        private int partitionId_;
        private com.google.protobuf.LazyStringList groupIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;

        // Construct using com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.flipkart.vbroker.proto.PRequests.internal_static_proto_GetPartSubscriptionOffsetsRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.flipkart.vbroker.proto.PRequests.internal_static_proto_GetPartSubscriptionOffsetsRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest.class, com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            partitionId_ = 0;

            groupIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            bitField0_ = (bitField0_ & ~0x00000002);
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.flipkart.vbroker.proto.PRequests.internal_static_proto_GetPartSubscriptionOffsetsRequest_descriptor;
        }

        public com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest getDefaultInstanceForType() {
            return com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest.getDefaultInstance();
        }

        public com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest build() {
            com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest buildPartial() {
            com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest result = new com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            result.partitionId_ = partitionId_;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                groupIds_ = groupIds_.getUnmodifiableView();
                bitField0_ = (bitField0_ & ~0x00000002);
            }
            result.groupIds_ = groupIds_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest) {
                return mergeFrom((com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest other) {
            if (other == com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest.getDefaultInstance()) return this;
            if (other.getPartitionId() != 0) {
                setPartitionId(other.getPartitionId());
            }
            if (!other.groupIds_.isEmpty()) {
                if (groupIds_.isEmpty()) {
                    groupIds_ = other.groupIds_;
                    bitField0_ = (bitField0_ & ~0x00000002);
                } else {
                    ensureGroupIdsIsMutable();
                    groupIds_.addAll(other.groupIds_);
                }
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>int32 partitionId = 1;</code>
         */
        public int getPartitionId() {
            return partitionId_;
        }

        /**
         * <code>int32 partitionId = 1;</code>
         */
        public Builder setPartitionId(int value) {

            partitionId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 partitionId = 1;</code>
         */
        public Builder clearPartitionId() {

            partitionId_ = 0;
            onChanged();
            return this;
        }

        private void ensureGroupIdsIsMutable() {
            if (!((bitField0_ & 0x00000002) == 0x00000002)) {
                groupIds_ = new com.google.protobuf.LazyStringArrayList(groupIds_);
                bitField0_ |= 0x00000002;
            }
        }

        /**
         * <code>repeated string groupIds = 2;</code>
         */
        public com.google.protobuf.ProtocolStringList
        getGroupIdsList() {
            return groupIds_.getUnmodifiableView();
        }

        /**
         * <code>repeated string groupIds = 2;</code>
         */
        public int getGroupIdsCount() {
            return groupIds_.size();
        }

        /**
         * <code>repeated string groupIds = 2;</code>
         */
        public java.lang.String getGroupIds(int index) {
            return groupIds_.get(index);
        }

        /**
         * <code>repeated string groupIds = 2;</code>
         */
        public com.google.protobuf.ByteString
        getGroupIdsBytes(int index) {
            return groupIds_.getByteString(index);
        }

        /**
         * <code>repeated string groupIds = 2;</code>
         */
        public Builder setGroupIds(
            int index, java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureGroupIdsIsMutable();
            groupIds_.set(index, value);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string groupIds = 2;</code>
         */
        public Builder addGroupIds(
            java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureGroupIdsIsMutable();
            groupIds_.add(value);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string groupIds = 2;</code>
         */
        public Builder addAllGroupIds(
            java.lang.Iterable<java.lang.String> values) {
            ensureGroupIdsIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, groupIds_);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string groupIds = 2;</code>
         */
        public Builder clearGroupIds() {
            groupIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string groupIds = 2;</code>
         */
        public Builder addGroupIdsBytes(
            com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            ensureGroupIdsIsMutable();
            groupIds_.add(value);
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:proto.GetPartSubscriptionOffsetsRequest)
    }

}

