// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests.proto

package com.flipkart.vbroker.proto;

public interface GetQueuesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetQueuesRequest)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 ids = 1;</code>
     */
    java.util.List<java.lang.Integer> getIdsList();

    /**
     * <code>repeated int32 ids = 1;</code>
     */
    int getIdsCount();

    /**
     * <code>repeated int32 ids = 1;</code>
     */
    int getIds(int index);
}
