// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests.proto

package com.flipkart.vbroker.proto;

/**
 * Protobuf type {@code proto.GetSubscriptionsOffsetsRequest}
 */
public final class GetSubscriptionsOffsetsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.GetSubscriptionsOffsetsRequest)
    GetSubscriptionsOffsetsRequestOrBuilder {
    public static final int GETSUBSCRIPTIONOFFSETSREQUESTS_FIELD_NUMBER = 1;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:proto.GetSubscriptionsOffsetsRequest)
    private static final com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<GetSubscriptionsOffsetsRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetSubscriptionsOffsetsRequest>() {
        public GetSubscriptionsOffsetsRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new GetSubscriptionsOffsetsRequest(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest();
    }

    private java.util.List<com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest> getSubscriptionOffsetsRequests_;
    private byte memoizedIsInitialized = -1;

    // Use GetSubscriptionsOffsetsRequest.newBuilder() to construct.
    private GetSubscriptionsOffsetsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }
    private GetSubscriptionsOffsetsRequest() {
        getSubscriptionOffsetsRequests_ = java.util.Collections.emptyList();
    }

    private GetSubscriptionsOffsetsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                            input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                            getSubscriptionOffsetsRequests_ = new java.util.ArrayList<com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest>();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        getSubscriptionOffsetsRequests_.add(
                            input.readMessage(com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest.parser(), extensionRegistry));
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                getSubscriptionOffsetsRequests_ = java.util.Collections.unmodifiableList(getSubscriptionOffsetsRequests_);
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.flipkart.vbroker.proto.PRequests.internal_static_proto_GetSubscriptionsOffsetsRequest_descriptor;
    }

    public static com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<GetSubscriptionsOffsetsRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.flipkart.vbroker.proto.PRequests.internal_static_proto_GetSubscriptionsOffsetsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest.class, com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest.Builder.class);
    }

    /**
     * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
     */
    public java.util.List<com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest> getGetSubscriptionOffsetsRequestsList() {
        return getSubscriptionOffsetsRequests_;
    }

    /**
     * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
     */
    public java.util.List<? extends com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequestOrBuilder>
    getGetSubscriptionOffsetsRequestsOrBuilderList() {
        return getSubscriptionOffsetsRequests_;
    }

    /**
     * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
     */
    public int getGetSubscriptionOffsetsRequestsCount() {
        return getSubscriptionOffsetsRequests_.size();
    }

    /**
     * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
     */
    public com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest getGetSubscriptionOffsetsRequests(int index) {
        return getSubscriptionOffsetsRequests_.get(index);
    }

    /**
     * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
     */
    public com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequestOrBuilder getGetSubscriptionOffsetsRequestsOrBuilder(
        int index) {
        return getSubscriptionOffsetsRequests_.get(index);
    }

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
        for (int i = 0; i < getSubscriptionOffsetsRequests_.size(); i++) {
            output.writeMessage(1, getSubscriptionOffsetsRequests_.get(i));
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < getSubscriptionOffsetsRequests_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(1, getSubscriptionOffsetsRequests_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest)) {
            return super.equals(obj);
        }
        com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest other = (com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest) obj;

        boolean result = true;
        result = result && getGetSubscriptionOffsetsRequestsList()
            .equals(other.getGetSubscriptionOffsetsRequestsList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getGetSubscriptionOffsetsRequestsCount() > 0) {
            hash = (37 * hash) + GETSUBSCRIPTIONOFFSETSREQUESTS_FIELD_NUMBER;
            hash = (53 * hash) + getGetSubscriptionOffsetsRequestsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetSubscriptionsOffsetsRequest> getParserForType() {
        return PARSER;
    }

    public com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code proto.GetSubscriptionsOffsetsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.GetSubscriptionsOffsetsRequest)
        com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequestOrBuilder {
        private int bitField0_;
        private java.util.List<com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest> getSubscriptionOffsetsRequests_ =
            java.util.Collections.emptyList();
        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest, com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest.Builder, com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequestOrBuilder> getSubscriptionOffsetsRequestsBuilder_;

        // Construct using com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.flipkart.vbroker.proto.PRequests.internal_static_proto_GetSubscriptionsOffsetsRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.flipkart.vbroker.proto.PRequests.internal_static_proto_GetSubscriptionsOffsetsRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest.class, com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
                getGetSubscriptionOffsetsRequestsFieldBuilder();
            }
        }

        public Builder clear() {
            super.clear();
            if (getSubscriptionOffsetsRequestsBuilder_ == null) {
                getSubscriptionOffsetsRequests_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
            } else {
                getSubscriptionOffsetsRequestsBuilder_.clear();
            }
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.flipkart.vbroker.proto.PRequests.internal_static_proto_GetSubscriptionsOffsetsRequest_descriptor;
        }

        public com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest getDefaultInstanceForType() {
            return com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest.getDefaultInstance();
        }

        public com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest build() {
            com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest buildPartial() {
            com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest result = new com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest(this);
            int from_bitField0_ = bitField0_;
            if (getSubscriptionOffsetsRequestsBuilder_ == null) {
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    getSubscriptionOffsetsRequests_ = java.util.Collections.unmodifiableList(getSubscriptionOffsetsRequests_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.getSubscriptionOffsetsRequests_ = getSubscriptionOffsetsRequests_;
            } else {
                result.getSubscriptionOffsetsRequests_ = getSubscriptionOffsetsRequestsBuilder_.build();
            }
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest) {
                return mergeFrom((com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest other) {
            if (other == com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest.getDefaultInstance()) return this;
            if (getSubscriptionOffsetsRequestsBuilder_ == null) {
                if (!other.getSubscriptionOffsetsRequests_.isEmpty()) {
                    if (getSubscriptionOffsetsRequests_.isEmpty()) {
                        getSubscriptionOffsetsRequests_ = other.getSubscriptionOffsetsRequests_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureGetSubscriptionOffsetsRequestsIsMutable();
                        getSubscriptionOffsetsRequests_.addAll(other.getSubscriptionOffsetsRequests_);
                    }
                    onChanged();
                }
            } else {
                if (!other.getSubscriptionOffsetsRequests_.isEmpty()) {
                    if (getSubscriptionOffsetsRequestsBuilder_.isEmpty()) {
                        getSubscriptionOffsetsRequestsBuilder_.dispose();
                        getSubscriptionOffsetsRequestsBuilder_ = null;
                        getSubscriptionOffsetsRequests_ = other.getSubscriptionOffsetsRequests_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                        getSubscriptionOffsetsRequestsBuilder_ =
                            com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                getGetSubscriptionOffsetsRequestsFieldBuilder() : null;
                    } else {
                        getSubscriptionOffsetsRequestsBuilder_.addAllMessages(other.getSubscriptionOffsetsRequests_);
                    }
                }
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.flipkart.vbroker.proto.GetSubscriptionsOffsetsRequest) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private void ensureGetSubscriptionOffsetsRequestsIsMutable() {
            if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                getSubscriptionOffsetsRequests_ = new java.util.ArrayList<com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest>(getSubscriptionOffsetsRequests_);
                bitField0_ |= 0x00000001;
            }
        }

        /**
         * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
         */
        public java.util.List<com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest> getGetSubscriptionOffsetsRequestsList() {
            if (getSubscriptionOffsetsRequestsBuilder_ == null) {
                return java.util.Collections.unmodifiableList(getSubscriptionOffsetsRequests_);
            } else {
                return getSubscriptionOffsetsRequestsBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
         */
        public int getGetSubscriptionOffsetsRequestsCount() {
            if (getSubscriptionOffsetsRequestsBuilder_ == null) {
                return getSubscriptionOffsetsRequests_.size();
            } else {
                return getSubscriptionOffsetsRequestsBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
         */
        public com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest getGetSubscriptionOffsetsRequests(int index) {
            if (getSubscriptionOffsetsRequestsBuilder_ == null) {
                return getSubscriptionOffsetsRequests_.get(index);
            } else {
                return getSubscriptionOffsetsRequestsBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
         */
        public Builder setGetSubscriptionOffsetsRequests(
            int index, com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest value) {
            if (getSubscriptionOffsetsRequestsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureGetSubscriptionOffsetsRequestsIsMutable();
                getSubscriptionOffsetsRequests_.set(index, value);
                onChanged();
            } else {
                getSubscriptionOffsetsRequestsBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
         */
        public Builder setGetSubscriptionOffsetsRequests(
            int index, com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest.Builder builderForValue) {
            if (getSubscriptionOffsetsRequestsBuilder_ == null) {
                ensureGetSubscriptionOffsetsRequestsIsMutable();
                getSubscriptionOffsetsRequests_.set(index, builderForValue.build());
                onChanged();
            } else {
                getSubscriptionOffsetsRequestsBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
         */
        public Builder addGetSubscriptionOffsetsRequests(com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest value) {
            if (getSubscriptionOffsetsRequestsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureGetSubscriptionOffsetsRequestsIsMutable();
                getSubscriptionOffsetsRequests_.add(value);
                onChanged();
            } else {
                getSubscriptionOffsetsRequestsBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
         */
        public Builder addGetSubscriptionOffsetsRequests(
            int index, com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest value) {
            if (getSubscriptionOffsetsRequestsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureGetSubscriptionOffsetsRequestsIsMutable();
                getSubscriptionOffsetsRequests_.add(index, value);
                onChanged();
            } else {
                getSubscriptionOffsetsRequestsBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
         */
        public Builder addGetSubscriptionOffsetsRequests(
            com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest.Builder builderForValue) {
            if (getSubscriptionOffsetsRequestsBuilder_ == null) {
                ensureGetSubscriptionOffsetsRequestsIsMutable();
                getSubscriptionOffsetsRequests_.add(builderForValue.build());
                onChanged();
            } else {
                getSubscriptionOffsetsRequestsBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
         */
        public Builder addGetSubscriptionOffsetsRequests(
            int index, com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest.Builder builderForValue) {
            if (getSubscriptionOffsetsRequestsBuilder_ == null) {
                ensureGetSubscriptionOffsetsRequestsIsMutable();
                getSubscriptionOffsetsRequests_.add(index, builderForValue.build());
                onChanged();
            } else {
                getSubscriptionOffsetsRequestsBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
         */
        public Builder addAllGetSubscriptionOffsetsRequests(
            java.lang.Iterable<? extends com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest> values) {
            if (getSubscriptionOffsetsRequestsBuilder_ == null) {
                ensureGetSubscriptionOffsetsRequestsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                    values, getSubscriptionOffsetsRequests_);
                onChanged();
            } else {
                getSubscriptionOffsetsRequestsBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
         */
        public Builder clearGetSubscriptionOffsetsRequests() {
            if (getSubscriptionOffsetsRequestsBuilder_ == null) {
                getSubscriptionOffsetsRequests_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
            } else {
                getSubscriptionOffsetsRequestsBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
         */
        public Builder removeGetSubscriptionOffsetsRequests(int index) {
            if (getSubscriptionOffsetsRequestsBuilder_ == null) {
                ensureGetSubscriptionOffsetsRequestsIsMutable();
                getSubscriptionOffsetsRequests_.remove(index);
                onChanged();
            } else {
                getSubscriptionOffsetsRequestsBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
         */
        public com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest.Builder getGetSubscriptionOffsetsRequestsBuilder(
            int index) {
            return getGetSubscriptionOffsetsRequestsFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
         */
        public com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequestOrBuilder getGetSubscriptionOffsetsRequestsOrBuilder(
            int index) {
            if (getSubscriptionOffsetsRequestsBuilder_ == null) {
                return getSubscriptionOffsetsRequests_.get(index);
            } else {
                return getSubscriptionOffsetsRequestsBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
         */
        public java.util.List<? extends com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequestOrBuilder>
        getGetSubscriptionOffsetsRequestsOrBuilderList() {
            if (getSubscriptionOffsetsRequestsBuilder_ != null) {
                return getSubscriptionOffsetsRequestsBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(getSubscriptionOffsetsRequests_);
            }
        }

        /**
         * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
         */
        public com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest.Builder addGetSubscriptionOffsetsRequestsBuilder() {
            return getGetSubscriptionOffsetsRequestsFieldBuilder().addBuilder(
                com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest.getDefaultInstance());
        }

        /**
         * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
         */
        public com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest.Builder addGetSubscriptionOffsetsRequestsBuilder(
            int index) {
            return getGetSubscriptionOffsetsRequestsFieldBuilder().addBuilder(
                index, com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest.getDefaultInstance());
        }

        /**
         * <code>repeated .proto.GetSubscriptionOffsetsRequest getSubscriptionOffsetsRequests = 1;</code>
         */
        public java.util.List<com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest.Builder>
        getGetSubscriptionOffsetsRequestsBuilderList() {
            return getGetSubscriptionOffsetsRequestsFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest, com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest.Builder, com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequestOrBuilder>
        getGetSubscriptionOffsetsRequestsFieldBuilder() {
            if (getSubscriptionOffsetsRequestsBuilder_ == null) {
                getSubscriptionOffsetsRequestsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                    com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest, com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequest.Builder, com.flipkart.vbroker.proto.GetSubscriptionOffsetsRequestOrBuilder>(
                    getSubscriptionOffsetsRequests_,
                    ((bitField0_ & 0x00000001) == 0x00000001),
                    getParentForChildren(),
                    isClean());
                getSubscriptionOffsetsRequests_ = null;
            }
            return getSubscriptionOffsetsRequestsBuilder_;
        }

        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:proto.GetSubscriptionsOffsetsRequest)
    }

}

