// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: responses.proto

package com.flipkart.vbroker.proto;

public interface GetSubscriptionOffsetsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetSubscriptionOffsetsResponse)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.TopicSubscription topicSubscription = 1;</code>
     */
    boolean hasTopicSubscription();

    /**
     * <code>.proto.TopicSubscription topicSubscription = 1;</code>
     */
    com.flipkart.vbroker.proto.TopicSubscription getTopicSubscription();

    /**
     * <code>.proto.TopicSubscription topicSubscription = 1;</code>
     */
    com.flipkart.vbroker.proto.TopicSubscriptionOrBuilder getTopicSubscriptionOrBuilder();

    /**
     * <code>repeated .proto.GetPartSubscriptionOffsetsResponse getPartSubscriptionOffsetsResponses = 2;</code>
     */
    java.util.List<com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsResponse>
    getGetPartSubscriptionOffsetsResponsesList();

    /**
     * <code>repeated .proto.GetPartSubscriptionOffsetsResponse getPartSubscriptionOffsetsResponses = 2;</code>
     */
    com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsResponse getGetPartSubscriptionOffsetsResponses(int index);

    /**
     * <code>repeated .proto.GetPartSubscriptionOffsetsResponse getPartSubscriptionOffsetsResponses = 2;</code>
     */
    int getGetPartSubscriptionOffsetsResponsesCount();

    /**
     * <code>repeated .proto.GetPartSubscriptionOffsetsResponse getPartSubscriptionOffsetsResponses = 2;</code>
     */
    java.util.List<? extends com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsResponseOrBuilder>
    getGetPartSubscriptionOffsetsResponsesOrBuilderList();

    /**
     * <code>repeated .proto.GetPartSubscriptionOffsetsResponse getPartSubscriptionOffsetsResponses = 2;</code>
     */
    com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsResponseOrBuilder getGetPartSubscriptionOffsetsResponsesOrBuilder(
        int index);
}
