// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests.proto

package com.flipkart.vbroker.proto;

public interface GetSubscriptionOffsetsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetSubscriptionOffsetsRequest)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.TopicSubscription topicSubscription = 1;</code>
     */
    boolean hasTopicSubscription();

    /**
     * <code>.proto.TopicSubscription topicSubscription = 1;</code>
     */
    com.flipkart.vbroker.proto.TopicSubscription getTopicSubscription();

    /**
     * <code>.proto.TopicSubscription topicSubscription = 1;</code>
     */
    com.flipkart.vbroker.proto.TopicSubscriptionOrBuilder getTopicSubscriptionOrBuilder();

    /**
     * <code>repeated .proto.GetPartSubscriptionOffsetsRequest getPartSubscriptionOffsetsRequests = 2;</code>
     */
    java.util.List<com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest>
    getGetPartSubscriptionOffsetsRequestsList();

    /**
     * <code>repeated .proto.GetPartSubscriptionOffsetsRequest getPartSubscriptionOffsetsRequests = 2;</code>
     */
    com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequest getGetPartSubscriptionOffsetsRequests(int index);

    /**
     * <code>repeated .proto.GetPartSubscriptionOffsetsRequest getPartSubscriptionOffsetsRequests = 2;</code>
     */
    int getGetPartSubscriptionOffsetsRequestsCount();

    /**
     * <code>repeated .proto.GetPartSubscriptionOffsetsRequest getPartSubscriptionOffsetsRequests = 2;</code>
     */
    java.util.List<? extends com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequestOrBuilder>
    getGetPartSubscriptionOffsetsRequestsOrBuilderList();

    /**
     * <code>repeated .proto.GetPartSubscriptionOffsetsRequest getPartSubscriptionOffsetsRequests = 2;</code>
     */
    com.flipkart.vbroker.proto.GetPartSubscriptionOffsetsRequestOrBuilder getGetPartSubscriptionOffsetsRequestsOrBuilder(
        int index);
}
