// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: responses.proto

package com.flipkart.vbroker.proto;

public interface GetTopicsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetTopicsResponse)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.GetTopicResponse topicResponses = 1;</code>
     */
    java.util.List<com.flipkart.vbroker.proto.GetTopicResponse>
    getTopicResponsesList();

    /**
     * <code>repeated .proto.GetTopicResponse topicResponses = 1;</code>
     */
    com.flipkart.vbroker.proto.GetTopicResponse getTopicResponses(int index);

    /**
     * <code>repeated .proto.GetTopicResponse topicResponses = 1;</code>
     */
    int getTopicResponsesCount();

    /**
     * <code>repeated .proto.GetTopicResponse topicResponses = 1;</code>
     */
    java.util.List<? extends com.flipkart.vbroker.proto.GetTopicResponseOrBuilder>
    getTopicResponsesOrBuilderList();

    /**
     * <code>repeated .proto.GetTopicResponse topicResponses = 1;</code>
     */
    com.flipkart.vbroker.proto.GetTopicResponseOrBuilder getTopicResponsesOrBuilder(
        int index);
}
