// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests.proto

package com.flipkart.vbroker.proto;

public interface GroupOffsetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GroupOffset)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string groupId = 1;</code>
     */
    java.lang.String getGroupId();

    /**
     * <code>string groupId = 1;</code>
     */
    com.google.protobuf.ByteString
    getGroupIdBytes();

    /**
     * <code>int32 offset = 2;</code>
     */
    int getOffset();
}
