// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entities.proto

package com.flipkart.vbroker.proto;

public final class PEntities {
  private PEntities() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ProtoTopic_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ProtoTopic_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_FilterKeyValues_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_FilterKeyValues_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CodeRange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CodeRange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CallbackConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CallbackConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ProtoSubscription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ProtoSubscription_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ProtoQueue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ProtoQueue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_TopicSubscription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_TopicSubscription_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Node_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Node_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PartitionMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PartitionMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_TopicMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_TopicMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ClusterMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ClusterMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016entities.proto\022\005proto\"\223\001\n\nProtoTopic\022\014" +
      "\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\017\n\007grouped\030\003 \001(" +
      "\010\022\022\n\npartitions\030\004 \001(\005\022\031\n\021replicationFact" +
      "or\030\005 \001(\005\022+\n\rtopicCategory\030\006 \001(\0162\024.proto." +
      "TopicCategory\".\n\017FilterKeyValues\022\013\n\003key\030" +
      "\001 \001(\t\022\016\n\006values\030\002 \001(\t\"%\n\tCodeRange\022\014\n\004fr" +
      "om\030\001 \001(\005\022\n\n\002to\030\002 \001(\005\"6\n\016CallbackConfig\022$" +
      "\n\ncodeRanges\030\001 \003(\0132\020.proto.CodeRange\"\261\003\n" +
      "\021ProtoSubscription\022\n\n\002id\030\001 \001(\005\022\017\n\007topicI" +
      "d\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\017\n\007grouped\030\004 \001(\010\022\023" +
      "\n\013parallelism\030\005 \001(\005\022\026\n\016requestTimeout\030\006 " +
      "\001(\005\0221\n\020subscriptionType\030\007 \001(\0162\027.proto.Su" +
      "bscriptionType\022;\n\025subscriptionMechanism\030" +
      "\010 \001(\0162\034.proto.SubscriptionMechanism\022\017\n\007h" +
      "ttpUri\030\t \001(\t\022%\n\nhttpMethod\030\n \001(\0162\021.proto" +
      ".HttpMethod\022\017\n\007elastic\030\013 \001(\010\022\026\n\016filterOp" +
      "erator\030\014 \001(\t\0223\n\023filterKeyValuesList\030\r \003(" +
      "\0132\026.proto.FilterKeyValues\022-\n\016callbackCon" +
      "fig\030\016 \001(\0132\025.proto.CallbackConfig\"j\n\nProt" +
      "oQueue\022\n\n\002id\030\001 \001(\005\022 \n\005topic\030\002 \001(\0132\021.prot" +
      "o.ProtoTopic\022.\n\014subscription\030\003 \001(\0132\030.pro" +
      "to.ProtoSubscription\"<\n\021TopicSubscriptio" +
      "n\022\026\n\016subscriptionId\030\001 \001(\005\022\017\n\007topicId\030\002 \001" +
      "(\005\":\n\004Node\022\020\n\010brokerId\030\001 \001(\005\022\016\n\006hostIp\030\002" +
      " \001(\t\022\020\n\010hostPort\030\003 \001(\005\"T\n\021PartitionMetad" +
      "ata\022\n\n\002id\030\001 \001(\005\022\017\n\007topicId\030\002 \001(\005\022\020\n\010lead" +
      "erId\030\003 \001(\005\022\020\n\010replicas\030\004 \003(\005\"g\n\rTopicMet" +
      "adata\022 \n\005topic\030\001 \001(\0132\021.proto.ProtoTopic\022" +
      "4\n\022partitionMetadatas\030\002 \003(\0132\030.proto.Part" +
      "itionMetadata\"[\n\017ClusterMetadata\022,\n\016topi" +
      "cMetadatas\030\001 \003(\0132\024.proto.TopicMetadata\022\032" +
      "\n\005nodes\030\002 \003(\0132\013.proto.Node*%\n\rTopicCateg" +
      "ory\022\t\n\005QUEUE\020\000\022\t\n\005TOPIC\020\001*6\n\nHttpMethod\022" +
      "\010\n\004POST\020\000\022\007\n\003PUT\020\001\022\n\n\006DELETE\020\002\022\t\n\005PATCH\020" +
      "\003*+\n\020SubscriptionType\022\n\n\006STATIC\020\000\022\013\n\007DYN" +
      "AMIC\020\001*+\n\025SubscriptionMechanism\022\010\n\004PUSH\020" +
      "\000\022\010\n\004PULL\020\001*+\n\016FilterOperator\022\006\n\002OR\020\000\022\007\n" +
      "\003NOR\020\001\022\010\n\004NAND\020\002B)\n\032com.flipkart.vbroker" +
      ".protoB\tPEntitiesP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_ProtoTopic_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ProtoTopic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ProtoTopic_descriptor,
        new java.lang.String[] { "Name", "Id", "Grouped", "Partitions", "ReplicationFactor", "TopicCategory", });
    internal_static_proto_FilterKeyValues_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_FilterKeyValues_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_FilterKeyValues_descriptor,
        new java.lang.String[] { "Key", "Values", });
    internal_static_proto_CodeRange_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_CodeRange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CodeRange_descriptor,
        new java.lang.String[] { "From", "To", });
    internal_static_proto_CallbackConfig_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_CallbackConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CallbackConfig_descriptor,
        new java.lang.String[] { "CodeRanges", });
    internal_static_proto_ProtoSubscription_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_ProtoSubscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ProtoSubscription_descriptor,
        new java.lang.String[] { "Id", "TopicId", "Name", "Grouped", "Parallelism", "RequestTimeout", "SubscriptionType", "SubscriptionMechanism", "HttpUri", "HttpMethod", "Elastic", "FilterOperator", "FilterKeyValuesList", "CallbackConfig", });
    internal_static_proto_ProtoQueue_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_ProtoQueue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ProtoQueue_descriptor,
        new java.lang.String[] { "Id", "Topic", "Subscription", });
    internal_static_proto_TopicSubscription_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_proto_TopicSubscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_TopicSubscription_descriptor,
        new java.lang.String[] { "SubscriptionId", "TopicId", });
    internal_static_proto_Node_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_proto_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Node_descriptor,
        new java.lang.String[] { "BrokerId", "HostIp", "HostPort", });
    internal_static_proto_PartitionMetadata_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_proto_PartitionMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PartitionMetadata_descriptor,
        new java.lang.String[] { "Id", "TopicId", "LeaderId", "Replicas", });
    internal_static_proto_TopicMetadata_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_proto_TopicMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_TopicMetadata_descriptor,
        new java.lang.String[] { "Topic", "PartitionMetadatas", });
    internal_static_proto_ClusterMetadata_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_proto_ClusterMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ClusterMetadata_descriptor,
        new java.lang.String[] { "TopicMetadatas", "Nodes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
