// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests.proto

package com.flipkart.vbroker.proto;

public final class PRequests {
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_ProtoRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_ProtoRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_CreateTopicsRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_CreateTopicsRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_CreateSubscriptionsRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_CreateSubscriptionsRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_CreateQueuesRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_CreateQueuesRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetQueuesRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetQueuesRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetAllQueuesRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetAllQueuesRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetTopicsRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetTopicsRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetAllTopicsRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetAllTopicsRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetSubscriptionsRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetSubscriptionsRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetAllSubscriptionsForTopicsRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetAllSubscriptionsForTopicsRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_PartitionLagRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_PartitionLagRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_SubscriptionLagRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_SubscriptionLagRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetSubscriptionLagsRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetSubscriptionLagsRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetClusterMetadataRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetClusterMetadataRequest_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
        descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\016requests.proto\022\005proto\032\016entities.proto\"" +
                "\353\005\n\014ProtoRequest\0229\n\023createTopicsRequest\030" +
                "\001 \001(\0132\032.proto.CreateTopicsRequestH\000\022G\n\032c" +
                "reateSubscriptionsRequest\030\002 \001(\0132!.proto." +
                "CreateSubscriptionsRequestH\000\0229\n\023createQu" +
                "euesRequest\030\003 \001(\0132\032.proto.CreateQueuesRe" +
                "questH\000\0223\n\020getTopicsRequest\030\004 \001(\0132\027.prot" +
                "o.GetTopicsRequestH\000\0229\n\023getAllTopicsRequ" +
                "est\030\005 \001(\0132\032.proto.GetAllTopicsRequestH\000\022" +
                "A\n\027getSubscriptionsRequest\030\006 \001(\0132\036.proto",
            ".GetSubscriptionsRequestH\000\022Y\n#getAllSubs" +
                "criptionsForTopicsRequest\030\007 \001(\0132*.proto." +
                "GetAllSubscriptionsForTopicsRequestH\000\0223\n" +
                "\020getQueuesRequest\030\010 \001(\0132\027.proto.GetQueue" +
                "sRequestH\000\0229\n\023getAllQueuesRequest\030\t \001(\0132" +
                "\032.proto.GetAllQueuesRequestH\000\022G\n\032getSubs" +
                "criptionLagsRequest\030\n \001(\0132!.proto.GetSub" +
                "scriptionLagsRequestH\000\022E\n\031getClusterMeta" +
                "dataRequest\030\013 \001(\0132 .proto.GetClusterMeta" +
                "dataRequestH\000B\016\n\014protoRequest\"8\n\023CreateT",
            "opicsRequest\022!\n\006topics\030\001 \003(\0132\021.proto.Pro" +
                "toTopic\"M\n\032CreateSubscriptionsRequest\022/\n" +
                "\rsubscriptions\030\001 \003(\0132\030.proto.ProtoSubscr" +
                "iption\"8\n\023CreateQueuesRequest\022!\n\006queues\030" +
                "\001 \003(\0132\021.proto.ProtoQueue\"\037\n\020GetQueuesReq" +
                "uest\022\013\n\003ids\030\001 \003(\005\"\025\n\023GetAllQueuesRequest" +
                "\"\037\n\020GetTopicsRequest\022\013\n\003ids\030\001 \003(\005\"\025\n\023Get" +
                "AllTopicsRequest\"J\n\027GetSubscriptionsRequ" +
                "est\022/\n\rsubscriptions\030\001 \003(\0132\030.proto.Topic" +
                "Subscription\"7\n#GetAllSubscriptionsForTo",
            "picsRequest\022\020\n\010topicIds\030\001 \003(\005\"*\n\023Partiti" +
                "onLagRequest\022\023\n\013partitionId\030\001 \001(\005\"\200\001\n\026Su" +
                "bscriptionLagRequest\0223\n\021topicSubscriptio" +
                "n\030\001 \001(\0132\030.proto.TopicSubscription\0221\n\rpar" +
                "titionLags\030\002 \003(\0132\032.proto.PartitionLagReq" +
                "uest\"\\\n\032GetSubscriptionLagsRequest\022>\n\027su" +
                "bscriptionLagRequests\030\001 \003(\0132\035.proto.Subs" +
                "criptionLagRequest\"-\n\031GetClusterMetadata" +
                "Request\022\020\n\010topicIds\030\001 \003(\005B)\n\032com.flipkar" +
                "t.vbroker.protoB\tPRequestsP\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                    descriptor = root;
                    return null;
                }
            };
        com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[]{
                    com.flipkart.vbroker.proto.PEntities.getDescriptor(),
                }, assigner);
        internal_static_proto_ProtoRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
        internal_static_proto_ProtoRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_ProtoRequest_descriptor,
            new java.lang.String[]{"CreateTopicsRequest", "CreateSubscriptionsRequest", "CreateQueuesRequest", "GetTopicsRequest", "GetAllTopicsRequest", "GetSubscriptionsRequest", "GetAllSubscriptionsForTopicsRequest", "GetQueuesRequest", "GetAllQueuesRequest", "GetSubscriptionLagsRequest", "GetClusterMetadataRequest", "ProtoRequest",});
        internal_static_proto_CreateTopicsRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
        internal_static_proto_CreateTopicsRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_CreateTopicsRequest_descriptor,
            new java.lang.String[]{"Topics",});
        internal_static_proto_CreateSubscriptionsRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
        internal_static_proto_CreateSubscriptionsRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_CreateSubscriptionsRequest_descriptor,
            new java.lang.String[]{"Subscriptions",});
        internal_static_proto_CreateQueuesRequest_descriptor =
            getDescriptor().getMessageTypes().get(3);
        internal_static_proto_CreateQueuesRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_CreateQueuesRequest_descriptor,
            new java.lang.String[]{"Queues",});
        internal_static_proto_GetQueuesRequest_descriptor =
            getDescriptor().getMessageTypes().get(4);
        internal_static_proto_GetQueuesRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetQueuesRequest_descriptor,
            new java.lang.String[]{"Ids",});
        internal_static_proto_GetAllQueuesRequest_descriptor =
            getDescriptor().getMessageTypes().get(5);
        internal_static_proto_GetAllQueuesRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetAllQueuesRequest_descriptor,
            new java.lang.String[]{});
        internal_static_proto_GetTopicsRequest_descriptor =
            getDescriptor().getMessageTypes().get(6);
        internal_static_proto_GetTopicsRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetTopicsRequest_descriptor,
            new java.lang.String[]{"Ids",});
        internal_static_proto_GetAllTopicsRequest_descriptor =
            getDescriptor().getMessageTypes().get(7);
        internal_static_proto_GetAllTopicsRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetAllTopicsRequest_descriptor,
            new java.lang.String[]{});
        internal_static_proto_GetSubscriptionsRequest_descriptor =
            getDescriptor().getMessageTypes().get(8);
        internal_static_proto_GetSubscriptionsRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetSubscriptionsRequest_descriptor,
            new java.lang.String[]{"Subscriptions",});
        internal_static_proto_GetAllSubscriptionsForTopicsRequest_descriptor =
            getDescriptor().getMessageTypes().get(9);
        internal_static_proto_GetAllSubscriptionsForTopicsRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetAllSubscriptionsForTopicsRequest_descriptor,
            new java.lang.String[]{"TopicIds",});
        internal_static_proto_PartitionLagRequest_descriptor =
            getDescriptor().getMessageTypes().get(10);
        internal_static_proto_PartitionLagRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_PartitionLagRequest_descriptor,
            new java.lang.String[]{"PartitionId",});
        internal_static_proto_SubscriptionLagRequest_descriptor =
            getDescriptor().getMessageTypes().get(11);
        internal_static_proto_SubscriptionLagRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_SubscriptionLagRequest_descriptor,
            new java.lang.String[]{"TopicSubscription", "PartitionLags",});
        internal_static_proto_GetSubscriptionLagsRequest_descriptor =
            getDescriptor().getMessageTypes().get(12);
        internal_static_proto_GetSubscriptionLagsRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetSubscriptionLagsRequest_descriptor,
            new java.lang.String[]{"SubscriptionLagRequests",});
        internal_static_proto_GetClusterMetadataRequest_descriptor =
            getDescriptor().getMessageTypes().get(13);
        internal_static_proto_GetClusterMetadataRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetClusterMetadataRequest_descriptor,
            new java.lang.String[]{"TopicIds",});
        com.flipkart.vbroker.proto.PEntities.getDescriptor();
    }
    private PRequests() {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
