// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: responses.proto

package com.flipkart.vbroker.proto;

public final class PResponses {
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_VStatus_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_VStatus_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_ProtoResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_ProtoResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_CreateTopicResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_CreateTopicResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_CreateTopicsResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_CreateTopicsResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_CreateSubscriptionResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_CreateSubscriptionResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_CreateSubscriptionsResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_CreateSubscriptionsResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_CreateQueueResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_CreateQueueResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_CreateQueuesResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_CreateQueuesResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetTopicResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetTopicResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetTopicsResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetTopicsResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetAllTopicsResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetAllTopicsResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetSubscriptionResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetSubscriptionResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetSubscriptionsResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetSubscriptionsResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetAllSubscriptionsForTopicResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetAllSubscriptionsForTopicResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetAllSubscriptionsForTopicsResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetAllSubscriptionsForTopicsResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetQueueResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetQueueResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetQueuesResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetQueuesResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetAllQueuesResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetAllQueuesResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_PartitionLag_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_PartitionLag_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_SubscriptionLag_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_SubscriptionLag_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetSubscriptionLagsResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetSubscriptionLagsResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetClusterMetadataResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetClusterMetadataResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_UnsidelineGroupResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_UnsidelineGroupResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_UnsidelineResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_UnsidelineResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_UnsidelineResponses_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_UnsidelineResponses_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GroupOffsetResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GroupOffsetResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_SetPartSubscriptionOffsetsResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_SetPartSubscriptionOffsetsResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_SetSubscriptionOffsetsResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_SetSubscriptionOffsetsResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_SetSubscriptionsOffsetsResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_SetSubscriptionsOffsetsResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetGroupOffsetResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetGroupOffsetResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetPartSubscriptionOffsetsResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetPartSubscriptionOffsetsResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetSubscriptionOffsetsResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetSubscriptionOffsetsResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_proto_GetSubscriptionsOffsetsResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_proto_GetSubscriptionsOffsetsResponse_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
        descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\017responses.proto\022\005proto\032\016entities.proto" +
                "\".\n\007VStatus\022\022\n\nstatusCode\030\001 \001(\005\022\017\n\007messa" +
                "ge\030\002 \001(\t\"\344\007\n\rProtoResponse\022;\n\024createTopi" +
                "csResponse\030\001 \001(\0132\033.proto.CreateTopicsRes" +
                "ponseH\000\022I\n\033createSubscriptionsResponse\030\002" +
                " \001(\0132\".proto.CreateSubscriptionsResponse" +
                "H\000\022;\n\024createQueuesResponse\030\003 \001(\0132\033.proto" +
                ".CreateQueuesResponseH\000\0225\n\021getTopicsResp" +
                "onse\030\004 \001(\0132\030.proto.GetTopicsResponseH\000\022;" +
                "\n\024getAllTopicsResponse\030\005 \001(\0132\033.proto.Get" +
                "AllTopicsResponseH\000\0225\n\021getQueuesResponse" +
                "\030\006 \001(\0132\030.proto.GetQueuesResponseH\000\022;\n\024ge" +
                "tAllQueuesResponse\030\007 \001(\0132\033.proto.GetAllQ" +
                "ueuesResponseH\000\022C\n\030getSubscriptionsRespo" +
                "nse\030\010 \001(\0132\037.proto.GetSubscriptionsRespon" +
                "seH\000\022[\n$getAllSubscriptionsForTopicsResp" +
                "onse\030\t \001(\0132+.proto.GetAllSubscriptionsFo" +
                "rTopicsResponseH\000\022I\n\033getSubscriptionLags" +
                "Response\030\n \001(\0132\".proto.GetSubscriptionLa" +
                "gsResponseH\000\022G\n\032getClusterMetadataRespon" +
                "se\030\013 \001(\0132!.proto.GetClusterMetadataRespo" +
                "nseH\000\022Q\n\037setSubscriptionsOffsetsResponse" +
                "\030\014 \001(\0132&.proto.SetSubscriptionsOffsetsRe" +
                "sponseH\000\022Q\n\037getSubscriptionsOffsetsRespo" +
                "nse\030\r \001(\0132&.proto.GetSubscriptionsOffset" +
                "sResponseH\000\0229\n\023unsidelineResponses\030\016 \001(\013" +
                "2\032.proto.UnsidelineResponsesH\000B\017\n\rprotoR" +
                "esponse\"C\n\023CreateTopicResponse\022\014\n\004name\030\002" +
                " \001(\t\022\036\n\006status\030\003 \001(\0132\016.proto.VStatus\"P\n\024" +
                "CreateTopicsResponse\0228\n\024createTopicsResp" +
                "onse\030\001 \003(\0132\032.proto.CreateTopicResponse\"[" +
                "\n\032CreateSubscriptionResponse\022\017\n\007topicId\030" +
                "\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\036\n\006status\030\004 \001(\0132\016.pr" +
                "oto.VStatus\"e\n\033CreateSubscriptionsRespon" +
                "se\022F\n\033createSubscriptionResponses\030\001 \003(\0132" +
                "!.proto.CreateSubscriptionResponse\"H\n\023Cr" +
                "eateQueueResponse\022\021\n\tqueueName\030\001 \001(\t\022\036\n\006" +
                "status\030\002 \001(\0132\016.proto.VStatus\"P\n\024CreateQu" +
                "euesResponse\0228\n\024createQueueResponses\030\001 \003" +
                "(\0132\032.proto.CreateQueueResponse\"T\n\020GetTop" +
                "icResponse\022 \n\005topic\030\001 \001(\0132\021.proto.ProtoT" +
                "opic\022\036\n\006status\030\002 \001(\0132\016.proto.VStatus\"D\n\021" +
                "GetTopicsResponse\022/\n\016topicResponses\030\001 \003(" +
                "\0132\027.proto.GetTopicResponse\"Y\n\024GetAllTopi" +
                "csResponse\022\036\n\006status\030\001 \001(\0132\016.proto.VStat" +
                "us\022!\n\006topics\030\002 \003(\0132\021.proto.ProtoTopic\"i\n" +
                "\027GetSubscriptionResponse\022.\n\014subscription" +
                "\030\001 \001(\0132\030.proto.ProtoSubscription\022\036\n\006stat" +
                "us\030\002 \001(\0132\016.proto.VStatus\"Y\n\030GetSubscript" +
                "ionsResponse\022=\n\025subscriptionResponses\030\001 " +
                "\003(\0132\036.proto.GetSubscriptionResponse\"\207\001\n#" +
                "GetAllSubscriptionsForTopicResponse\022\017\n\007t" +
                "opicId\030\001 \001(\005\022\036\n\006status\030\002 \001(\0132\016.proto.VSt" +
                "atus\022/\n\rsubscriptions\030\003 \003(\0132\030.proto.Prot" +
                "oSubscription\"\200\001\n$GetAllSubscriptionsFor" +
                "TopicsResponse\022X\n$getAllSubscriptionsFor" +
                "TopicResponses\030\001 \003(\0132*.proto.GetAllSubsc" +
                "riptionsForTopicResponse\"T\n\020GetQueueResp" +
                "onse\022 \n\005queue\030\001 \001(\0132\021.proto.ProtoQueue\022\036" +
                "\n\006status\030\002 \001(\0132\016.proto.VStatus\"D\n\021GetQue" +
                "uesResponse\022/\n\016queueResponses\030\001 \003(\0132\027.pr" +
                "oto.GetQueueResponse\"Y\n\024GetAllQueuesResp" +
                "onse\022\036\n\006status\030\001 \001(\0132\016.proto.VStatus\022!\n\006" +
                "queues\030\002 \003(\0132\021.proto.ProtoQueue\"P\n\014Parti" +
                "tionLag\022\023\n\013partitionId\030\001 \001(\005\022\013\n\003lag\030\002 \001(" +
                "\005\022\036\n\006status\030\003 \001(\0132\016.proto.VStatus\"f\n\017Sub" +
                "scriptionLag\022\026\n\016subscriptionId\030\001 \001(\005\022\017\n\007" +
                "topicId\030\002 \001(\005\022*\n\rpartitionLags\030\003 \003(\0132\023.p" +
                "roto.PartitionLag\"O\n\033GetSubscriptionLags" +
                "Response\0220\n\020subscriptionLags\030\001 \003(\0132\026.pro" +
                "to.SubscriptionLag\"m\n\032GetClusterMetadata" +
                "Response\022/\n\017clusterMetadata\030\001 \001(\0132\026.prot" +
                "o.ClusterMetadata\022\036\n\006status\030\002 \001(\0132\016.prot" +
                "o.VStatus\"J\n\027UnsidelineGroupResponse\022\017\n\007" +
                "groupId\030\001 \001(\t\022\036\n\006status\030\002 \001(\0132\016.proto.VS" +
                "tatus\"\213\001\n\022UnsidelineResponse\0223\n\021topicSub" +
                "scription\030\001 \001(\0132\030.proto.TopicSubscriptio" +
                "n\022@\n\030unsidelineGroupResponses\030\002 \003(\0132\036.pr" +
                "oto.UnsidelineGroupResponse\"M\n\023Unsidelin" +
                "eResponses\0226\n\023unsidelineResponses\030\001 \003(\0132" +
                "\031.proto.UnsidelineResponse\"F\n\023GroupOffse" +
                "tResponse\022\017\n\007groupId\030\001 \001(\t\022\036\n\006status\030\002 \001" +
                "(\0132\016.proto.VStatus\"s\n\"SetPartSubscriptio" +
                "nOffsetsResponse\022\023\n\013partitionId\030\001 \001(\005\0228\n" +
                "\024groupOffsetResponses\030\002 \003(\0132\032.proto.Grou" +
                "pOffsetResponse\"\255\001\n\036SetSubscriptionOffse" +
                "tsResponse\0223\n\021topicSubscription\030\001 \001(\0132\030." +
                "proto.TopicSubscription\022V\n#setPartSubscr" +
                "iptionOffsetsResponses\030\002 \003(\0132).proto.Set" +
                "PartSubscriptionOffsetsResponse\"q\n\037SetSu" +
                "bscriptionsOffsetsResponse\022N\n\037setSubscri" +
                "ptionOffsetsResponses\030\001 \003(\0132%.proto.SetS" +
                "ubscriptionOffsetsResponse\"Y\n\026GetGroupOf" +
                "fsetResponse\022\017\n\007groupId\030\001 \001(\t\022\016\n\006offset\030" +
                "\002 \001(\005\022\036\n\006status\030\003 \001(\0132\016.proto.VStatus\"y\n" +
                "\"GetPartSubscriptionOffsetsResponse\022\023\n\013p" +
                "artitionId\030\001 \001(\005\022>\n\027getGroupOffsetRespon" +
                "ses\030\002 \003(\0132\035.proto.GetGroupOffsetResponse" +
                "\"\255\001\n\036GetSubscriptionOffsetsResponse\0223\n\021t" +
                "opicSubscription\030\001 \001(\0132\030.proto.TopicSubs" +
                "cription\022V\n#getPartSubscriptionOffsetsRe" +
                "sponses\030\002 \003(\0132).proto.GetPartSubscriptio" +
                "nOffsetsResponse\"q\n\037GetSubscriptionsOffs" +
                "etsResponse\022N\n\037getSubscriptionOffsetsRes" +
                "ponses\030\001 \003(\0132%.proto.GetSubscriptionOffs" +
                "etsResponseB*\n\032com.flipkart.vbroker.prot" +
                "oB\nPResponsesP\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                    descriptor = root;
                    return null;
                }
            };
        com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[]{
                    com.flipkart.vbroker.proto.PEntities.getDescriptor(),
                }, assigner);
        internal_static_proto_VStatus_descriptor =
            getDescriptor().getMessageTypes().get(0);
        internal_static_proto_VStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_VStatus_descriptor,
            new java.lang.String[]{"StatusCode", "Message",});
        internal_static_proto_ProtoResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
        internal_static_proto_ProtoResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_ProtoResponse_descriptor,
            new java.lang.String[]{"CreateTopicsResponse", "CreateSubscriptionsResponse", "CreateQueuesResponse", "GetTopicsResponse", "GetAllTopicsResponse", "GetQueuesResponse", "GetAllQueuesResponse", "GetSubscriptionsResponse", "GetAllSubscriptionsForTopicsResponse", "GetSubscriptionLagsResponse", "GetClusterMetadataResponse", "SetSubscriptionsOffsetsResponse", "GetSubscriptionsOffsetsResponse", "UnsidelineResponses", "ProtoResponse",});
        internal_static_proto_CreateTopicResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
        internal_static_proto_CreateTopicResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_CreateTopicResponse_descriptor,
            new java.lang.String[]{"Name", "Status",});
        internal_static_proto_CreateTopicsResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
        internal_static_proto_CreateTopicsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_CreateTopicsResponse_descriptor,
            new java.lang.String[]{"CreateTopicsResponse",});
        internal_static_proto_CreateSubscriptionResponse_descriptor =
            getDescriptor().getMessageTypes().get(4);
        internal_static_proto_CreateSubscriptionResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_CreateSubscriptionResponse_descriptor,
            new java.lang.String[]{"TopicId", "Name", "Status",});
        internal_static_proto_CreateSubscriptionsResponse_descriptor =
            getDescriptor().getMessageTypes().get(5);
        internal_static_proto_CreateSubscriptionsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_CreateSubscriptionsResponse_descriptor,
            new java.lang.String[]{"CreateSubscriptionResponses",});
        internal_static_proto_CreateQueueResponse_descriptor =
            getDescriptor().getMessageTypes().get(6);
        internal_static_proto_CreateQueueResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_CreateQueueResponse_descriptor,
            new java.lang.String[]{"QueueName", "Status",});
        internal_static_proto_CreateQueuesResponse_descriptor =
            getDescriptor().getMessageTypes().get(7);
        internal_static_proto_CreateQueuesResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_CreateQueuesResponse_descriptor,
            new java.lang.String[]{"CreateQueueResponses",});
        internal_static_proto_GetTopicResponse_descriptor =
            getDescriptor().getMessageTypes().get(8);
        internal_static_proto_GetTopicResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetTopicResponse_descriptor,
            new java.lang.String[]{"Topic", "Status",});
        internal_static_proto_GetTopicsResponse_descriptor =
            getDescriptor().getMessageTypes().get(9);
        internal_static_proto_GetTopicsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetTopicsResponse_descriptor,
            new java.lang.String[]{"TopicResponses",});
        internal_static_proto_GetAllTopicsResponse_descriptor =
            getDescriptor().getMessageTypes().get(10);
        internal_static_proto_GetAllTopicsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetAllTopicsResponse_descriptor,
            new java.lang.String[]{"Status", "Topics",});
        internal_static_proto_GetSubscriptionResponse_descriptor =
            getDescriptor().getMessageTypes().get(11);
        internal_static_proto_GetSubscriptionResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetSubscriptionResponse_descriptor,
            new java.lang.String[]{"Subscription", "Status",});
        internal_static_proto_GetSubscriptionsResponse_descriptor =
            getDescriptor().getMessageTypes().get(12);
        internal_static_proto_GetSubscriptionsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetSubscriptionsResponse_descriptor,
            new java.lang.String[]{"SubscriptionResponses",});
        internal_static_proto_GetAllSubscriptionsForTopicResponse_descriptor =
            getDescriptor().getMessageTypes().get(13);
        internal_static_proto_GetAllSubscriptionsForTopicResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetAllSubscriptionsForTopicResponse_descriptor,
            new java.lang.String[]{"TopicId", "Status", "Subscriptions",});
        internal_static_proto_GetAllSubscriptionsForTopicsResponse_descriptor =
            getDescriptor().getMessageTypes().get(14);
        internal_static_proto_GetAllSubscriptionsForTopicsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetAllSubscriptionsForTopicsResponse_descriptor,
            new java.lang.String[]{"GetAllSubscriptionsForTopicResponses",});
        internal_static_proto_GetQueueResponse_descriptor =
            getDescriptor().getMessageTypes().get(15);
        internal_static_proto_GetQueueResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetQueueResponse_descriptor,
            new java.lang.String[]{"Queue", "Status",});
        internal_static_proto_GetQueuesResponse_descriptor =
            getDescriptor().getMessageTypes().get(16);
        internal_static_proto_GetQueuesResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetQueuesResponse_descriptor,
            new java.lang.String[]{"QueueResponses",});
        internal_static_proto_GetAllQueuesResponse_descriptor =
            getDescriptor().getMessageTypes().get(17);
        internal_static_proto_GetAllQueuesResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetAllQueuesResponse_descriptor,
            new java.lang.String[]{"Status", "Queues",});
        internal_static_proto_PartitionLag_descriptor =
            getDescriptor().getMessageTypes().get(18);
        internal_static_proto_PartitionLag_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_PartitionLag_descriptor,
            new java.lang.String[]{"PartitionId", "Lag", "Status",});
        internal_static_proto_SubscriptionLag_descriptor =
            getDescriptor().getMessageTypes().get(19);
        internal_static_proto_SubscriptionLag_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_SubscriptionLag_descriptor,
            new java.lang.String[]{"SubscriptionId", "TopicId", "PartitionLags",});
        internal_static_proto_GetSubscriptionLagsResponse_descriptor =
            getDescriptor().getMessageTypes().get(20);
        internal_static_proto_GetSubscriptionLagsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetSubscriptionLagsResponse_descriptor,
            new java.lang.String[]{"SubscriptionLags",});
        internal_static_proto_GetClusterMetadataResponse_descriptor =
            getDescriptor().getMessageTypes().get(21);
        internal_static_proto_GetClusterMetadataResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetClusterMetadataResponse_descriptor,
            new java.lang.String[]{"ClusterMetadata", "Status",});
        internal_static_proto_UnsidelineGroupResponse_descriptor =
            getDescriptor().getMessageTypes().get(22);
        internal_static_proto_UnsidelineGroupResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_UnsidelineGroupResponse_descriptor,
            new java.lang.String[]{"GroupId", "Status",});
        internal_static_proto_UnsidelineResponse_descriptor =
            getDescriptor().getMessageTypes().get(23);
        internal_static_proto_UnsidelineResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_UnsidelineResponse_descriptor,
            new java.lang.String[]{"TopicSubscription", "UnsidelineGroupResponses",});
        internal_static_proto_UnsidelineResponses_descriptor =
            getDescriptor().getMessageTypes().get(24);
        internal_static_proto_UnsidelineResponses_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_UnsidelineResponses_descriptor,
            new java.lang.String[]{"UnsidelineResponses",});
        internal_static_proto_GroupOffsetResponse_descriptor =
            getDescriptor().getMessageTypes().get(25);
        internal_static_proto_GroupOffsetResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GroupOffsetResponse_descriptor,
            new java.lang.String[]{"GroupId", "Status",});
        internal_static_proto_SetPartSubscriptionOffsetsResponse_descriptor =
            getDescriptor().getMessageTypes().get(26);
        internal_static_proto_SetPartSubscriptionOffsetsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_SetPartSubscriptionOffsetsResponse_descriptor,
            new java.lang.String[]{"PartitionId", "GroupOffsetResponses",});
        internal_static_proto_SetSubscriptionOffsetsResponse_descriptor =
            getDescriptor().getMessageTypes().get(27);
        internal_static_proto_SetSubscriptionOffsetsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_SetSubscriptionOffsetsResponse_descriptor,
            new java.lang.String[]{"TopicSubscription", "SetPartSubscriptionOffsetsResponses",});
        internal_static_proto_SetSubscriptionsOffsetsResponse_descriptor =
            getDescriptor().getMessageTypes().get(28);
        internal_static_proto_SetSubscriptionsOffsetsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_SetSubscriptionsOffsetsResponse_descriptor,
            new java.lang.String[]{"SetSubscriptionOffsetsResponses",});
        internal_static_proto_GetGroupOffsetResponse_descriptor =
            getDescriptor().getMessageTypes().get(29);
        internal_static_proto_GetGroupOffsetResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetGroupOffsetResponse_descriptor,
            new java.lang.String[]{"GroupId", "Offset", "Status",});
        internal_static_proto_GetPartSubscriptionOffsetsResponse_descriptor =
            getDescriptor().getMessageTypes().get(30);
        internal_static_proto_GetPartSubscriptionOffsetsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetPartSubscriptionOffsetsResponse_descriptor,
            new java.lang.String[]{"PartitionId", "GetGroupOffsetResponses",});
        internal_static_proto_GetSubscriptionOffsetsResponse_descriptor =
            getDescriptor().getMessageTypes().get(31);
        internal_static_proto_GetSubscriptionOffsetsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetSubscriptionOffsetsResponse_descriptor,
            new java.lang.String[]{"TopicSubscription", "GetPartSubscriptionOffsetsResponses",});
        internal_static_proto_GetSubscriptionsOffsetsResponse_descriptor =
            getDescriptor().getMessageTypes().get(32);
        internal_static_proto_GetSubscriptionsOffsetsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_proto_GetSubscriptionsOffsetsResponse_descriptor,
            new java.lang.String[]{"GetSubscriptionOffsetsResponses",});
        com.flipkart.vbroker.proto.PEntities.getDescriptor();
    }
    private PResponses() {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
