// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests.proto

package com.flipkart.vbroker.proto;

public interface SetSubscriptionsOffsetsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.SetSubscriptionsOffsetsRequest)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.SetSubscriptionOffsetsRequest setSubscriptionOffsetsRequests = 1;</code>
     */
    java.util.List<com.flipkart.vbroker.proto.SetSubscriptionOffsetsRequest>
    getSetSubscriptionOffsetsRequestsList();

    /**
     * <code>repeated .proto.SetSubscriptionOffsetsRequest setSubscriptionOffsetsRequests = 1;</code>
     */
    com.flipkart.vbroker.proto.SetSubscriptionOffsetsRequest getSetSubscriptionOffsetsRequests(int index);

    /**
     * <code>repeated .proto.SetSubscriptionOffsetsRequest setSubscriptionOffsetsRequests = 1;</code>
     */
    int getSetSubscriptionOffsetsRequestsCount();

    /**
     * <code>repeated .proto.SetSubscriptionOffsetsRequest setSubscriptionOffsetsRequests = 1;</code>
     */
    java.util.List<? extends com.flipkart.vbroker.proto.SetSubscriptionOffsetsRequestOrBuilder>
    getSetSubscriptionOffsetsRequestsOrBuilderList();

    /**
     * <code>repeated .proto.SetSubscriptionOffsetsRequest setSubscriptionOffsetsRequests = 1;</code>
     */
    com.flipkart.vbroker.proto.SetSubscriptionOffsetsRequestOrBuilder getSetSubscriptionOffsetsRequestsOrBuilder(
        int index);
}
