// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests.proto

package com.flipkart.vbroker.proto;

public interface SubscriptionLagRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.SubscriptionLagRequest)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.TopicSubscription topicSubscription = 1;</code>
     */
    boolean hasTopicSubscription();

    /**
     * <code>.proto.TopicSubscription topicSubscription = 1;</code>
     */
    com.flipkart.vbroker.proto.TopicSubscription getTopicSubscription();

    /**
     * <code>.proto.TopicSubscription topicSubscription = 1;</code>
     */
    com.flipkart.vbroker.proto.TopicSubscriptionOrBuilder getTopicSubscriptionOrBuilder();

    /**
     * <code>repeated .proto.PartitionLagRequest partitionLags = 2;</code>
     */
    java.util.List<com.flipkart.vbroker.proto.PartitionLagRequest>
    getPartitionLagsList();

    /**
     * <code>repeated .proto.PartitionLagRequest partitionLags = 2;</code>
     */
    com.flipkart.vbroker.proto.PartitionLagRequest getPartitionLags(int index);

    /**
     * <code>repeated .proto.PartitionLagRequest partitionLags = 2;</code>
     */
    int getPartitionLagsCount();

    /**
     * <code>repeated .proto.PartitionLagRequest partitionLags = 2;</code>
     */
    java.util.List<? extends com.flipkart.vbroker.proto.PartitionLagRequestOrBuilder>
    getPartitionLagsOrBuilderList();

    /**
     * <code>repeated .proto.PartitionLagRequest partitionLags = 2;</code>
     */
    com.flipkart.vbroker.proto.PartitionLagRequestOrBuilder getPartitionLagsOrBuilder(
        int index);
}
