// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests.proto

package com.flipkart.vbroker.proto;

/**
 * Protobuf type {@code proto.UnsidelineRequests}
 */
public final class UnsidelineRequests extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.UnsidelineRequests)
    UnsidelineRequestsOrBuilder {
    public static final int UNSIDELINEREQUESTS_FIELD_NUMBER = 1;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:proto.UnsidelineRequests)
    private static final com.flipkart.vbroker.proto.UnsidelineRequests DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<UnsidelineRequests>
        PARSER = new com.google.protobuf.AbstractParser<UnsidelineRequests>() {
        public UnsidelineRequests parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new UnsidelineRequests(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new com.flipkart.vbroker.proto.UnsidelineRequests();
    }

    private java.util.List<com.flipkart.vbroker.proto.UnsidelineRequest> unsidelineRequests_;
    private byte memoizedIsInitialized = -1;

    // Use UnsidelineRequests.newBuilder() to construct.
    private UnsidelineRequests(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }
    private UnsidelineRequests() {
        unsidelineRequests_ = java.util.Collections.emptyList();
    }

    private UnsidelineRequests(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                            input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                            unsidelineRequests_ = new java.util.ArrayList<com.flipkart.vbroker.proto.UnsidelineRequest>();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        unsidelineRequests_.add(
                            input.readMessage(com.flipkart.vbroker.proto.UnsidelineRequest.parser(), extensionRegistry));
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                unsidelineRequests_ = java.util.Collections.unmodifiableList(unsidelineRequests_);
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.flipkart.vbroker.proto.PRequests.internal_static_proto_UnsidelineRequests_descriptor;
    }

    public static com.flipkart.vbroker.proto.UnsidelineRequests parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.flipkart.vbroker.proto.UnsidelineRequests parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.UnsidelineRequests parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.flipkart.vbroker.proto.UnsidelineRequests parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.UnsidelineRequests parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.flipkart.vbroker.proto.UnsidelineRequests parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.UnsidelineRequests parseFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static com.flipkart.vbroker.proto.UnsidelineRequests parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.UnsidelineRequests parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.flipkart.vbroker.proto.UnsidelineRequests parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.flipkart.vbroker.proto.UnsidelineRequests parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static com.flipkart.vbroker.proto.UnsidelineRequests parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.flipkart.vbroker.proto.UnsidelineRequests prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.flipkart.vbroker.proto.UnsidelineRequests getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<UnsidelineRequests> parser() {
        return PARSER;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.flipkart.vbroker.proto.PRequests.internal_static_proto_UnsidelineRequests_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.flipkart.vbroker.proto.UnsidelineRequests.class, com.flipkart.vbroker.proto.UnsidelineRequests.Builder.class);
    }

    /**
     * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
     */
    public java.util.List<com.flipkart.vbroker.proto.UnsidelineRequest> getUnsidelineRequestsList() {
        return unsidelineRequests_;
    }

    /**
     * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
     */
    public java.util.List<? extends com.flipkart.vbroker.proto.UnsidelineRequestOrBuilder>
    getUnsidelineRequestsOrBuilderList() {
        return unsidelineRequests_;
    }

    /**
     * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
     */
    public int getUnsidelineRequestsCount() {
        return unsidelineRequests_.size();
    }

    /**
     * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
     */
    public com.flipkart.vbroker.proto.UnsidelineRequest getUnsidelineRequests(int index) {
        return unsidelineRequests_.get(index);
    }

    /**
     * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
     */
    public com.flipkart.vbroker.proto.UnsidelineRequestOrBuilder getUnsidelineRequestsOrBuilder(
        int index) {
        return unsidelineRequests_.get(index);
    }

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
        for (int i = 0; i < unsidelineRequests_.size(); i++) {
            output.writeMessage(1, unsidelineRequests_.get(i));
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < unsidelineRequests_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(1, unsidelineRequests_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.flipkart.vbroker.proto.UnsidelineRequests)) {
            return super.equals(obj);
        }
        com.flipkart.vbroker.proto.UnsidelineRequests other = (com.flipkart.vbroker.proto.UnsidelineRequests) obj;

        boolean result = true;
        result = result && getUnsidelineRequestsList()
            .equals(other.getUnsidelineRequestsList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getUnsidelineRequestsCount() > 0) {
            hash = (37 * hash) + UNSIDELINEREQUESTS_FIELD_NUMBER;
            hash = (53 * hash) + getUnsidelineRequestsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UnsidelineRequests> getParserForType() {
        return PARSER;
    }

    public com.flipkart.vbroker.proto.UnsidelineRequests getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code proto.UnsidelineRequests}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.UnsidelineRequests)
        com.flipkart.vbroker.proto.UnsidelineRequestsOrBuilder {
        private int bitField0_;
        private java.util.List<com.flipkart.vbroker.proto.UnsidelineRequest> unsidelineRequests_ =
            java.util.Collections.emptyList();
        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.flipkart.vbroker.proto.UnsidelineRequest, com.flipkart.vbroker.proto.UnsidelineRequest.Builder, com.flipkart.vbroker.proto.UnsidelineRequestOrBuilder> unsidelineRequestsBuilder_;

        // Construct using com.flipkart.vbroker.proto.UnsidelineRequests.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.flipkart.vbroker.proto.PRequests.internal_static_proto_UnsidelineRequests_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.flipkart.vbroker.proto.PRequests.internal_static_proto_UnsidelineRequests_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.flipkart.vbroker.proto.UnsidelineRequests.class, com.flipkart.vbroker.proto.UnsidelineRequests.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
                getUnsidelineRequestsFieldBuilder();
            }
        }

        public Builder clear() {
            super.clear();
            if (unsidelineRequestsBuilder_ == null) {
                unsidelineRequests_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
            } else {
                unsidelineRequestsBuilder_.clear();
            }
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.flipkart.vbroker.proto.PRequests.internal_static_proto_UnsidelineRequests_descriptor;
        }

        public com.flipkart.vbroker.proto.UnsidelineRequests getDefaultInstanceForType() {
            return com.flipkart.vbroker.proto.UnsidelineRequests.getDefaultInstance();
        }

        public com.flipkart.vbroker.proto.UnsidelineRequests build() {
            com.flipkart.vbroker.proto.UnsidelineRequests result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public com.flipkart.vbroker.proto.UnsidelineRequests buildPartial() {
            com.flipkart.vbroker.proto.UnsidelineRequests result = new com.flipkart.vbroker.proto.UnsidelineRequests(this);
            int from_bitField0_ = bitField0_;
            if (unsidelineRequestsBuilder_ == null) {
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    unsidelineRequests_ = java.util.Collections.unmodifiableList(unsidelineRequests_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.unsidelineRequests_ = unsidelineRequests_;
            } else {
                result.unsidelineRequests_ = unsidelineRequestsBuilder_.build();
            }
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.flipkart.vbroker.proto.UnsidelineRequests) {
                return mergeFrom((com.flipkart.vbroker.proto.UnsidelineRequests) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.flipkart.vbroker.proto.UnsidelineRequests other) {
            if (other == com.flipkart.vbroker.proto.UnsidelineRequests.getDefaultInstance()) return this;
            if (unsidelineRequestsBuilder_ == null) {
                if (!other.unsidelineRequests_.isEmpty()) {
                    if (unsidelineRequests_.isEmpty()) {
                        unsidelineRequests_ = other.unsidelineRequests_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureUnsidelineRequestsIsMutable();
                        unsidelineRequests_.addAll(other.unsidelineRequests_);
                    }
                    onChanged();
                }
            } else {
                if (!other.unsidelineRequests_.isEmpty()) {
                    if (unsidelineRequestsBuilder_.isEmpty()) {
                        unsidelineRequestsBuilder_.dispose();
                        unsidelineRequestsBuilder_ = null;
                        unsidelineRequests_ = other.unsidelineRequests_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                        unsidelineRequestsBuilder_ =
                            com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                getUnsidelineRequestsFieldBuilder() : null;
                    } else {
                        unsidelineRequestsBuilder_.addAllMessages(other.unsidelineRequests_);
                    }
                }
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            com.flipkart.vbroker.proto.UnsidelineRequests parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.flipkart.vbroker.proto.UnsidelineRequests) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private void ensureUnsidelineRequestsIsMutable() {
            if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                unsidelineRequests_ = new java.util.ArrayList<com.flipkart.vbroker.proto.UnsidelineRequest>(unsidelineRequests_);
                bitField0_ |= 0x00000001;
            }
        }

        /**
         * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
         */
        public java.util.List<com.flipkart.vbroker.proto.UnsidelineRequest> getUnsidelineRequestsList() {
            if (unsidelineRequestsBuilder_ == null) {
                return java.util.Collections.unmodifiableList(unsidelineRequests_);
            } else {
                return unsidelineRequestsBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
         */
        public int getUnsidelineRequestsCount() {
            if (unsidelineRequestsBuilder_ == null) {
                return unsidelineRequests_.size();
            } else {
                return unsidelineRequestsBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
         */
        public com.flipkart.vbroker.proto.UnsidelineRequest getUnsidelineRequests(int index) {
            if (unsidelineRequestsBuilder_ == null) {
                return unsidelineRequests_.get(index);
            } else {
                return unsidelineRequestsBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
         */
        public Builder setUnsidelineRequests(
            int index, com.flipkart.vbroker.proto.UnsidelineRequest value) {
            if (unsidelineRequestsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureUnsidelineRequestsIsMutable();
                unsidelineRequests_.set(index, value);
                onChanged();
            } else {
                unsidelineRequestsBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
         */
        public Builder setUnsidelineRequests(
            int index, com.flipkart.vbroker.proto.UnsidelineRequest.Builder builderForValue) {
            if (unsidelineRequestsBuilder_ == null) {
                ensureUnsidelineRequestsIsMutable();
                unsidelineRequests_.set(index, builderForValue.build());
                onChanged();
            } else {
                unsidelineRequestsBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
         */
        public Builder addUnsidelineRequests(com.flipkart.vbroker.proto.UnsidelineRequest value) {
            if (unsidelineRequestsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureUnsidelineRequestsIsMutable();
                unsidelineRequests_.add(value);
                onChanged();
            } else {
                unsidelineRequestsBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
         */
        public Builder addUnsidelineRequests(
            int index, com.flipkart.vbroker.proto.UnsidelineRequest value) {
            if (unsidelineRequestsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureUnsidelineRequestsIsMutable();
                unsidelineRequests_.add(index, value);
                onChanged();
            } else {
                unsidelineRequestsBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
         */
        public Builder addUnsidelineRequests(
            com.flipkart.vbroker.proto.UnsidelineRequest.Builder builderForValue) {
            if (unsidelineRequestsBuilder_ == null) {
                ensureUnsidelineRequestsIsMutable();
                unsidelineRequests_.add(builderForValue.build());
                onChanged();
            } else {
                unsidelineRequestsBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
         */
        public Builder addUnsidelineRequests(
            int index, com.flipkart.vbroker.proto.UnsidelineRequest.Builder builderForValue) {
            if (unsidelineRequestsBuilder_ == null) {
                ensureUnsidelineRequestsIsMutable();
                unsidelineRequests_.add(index, builderForValue.build());
                onChanged();
            } else {
                unsidelineRequestsBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
         */
        public Builder addAllUnsidelineRequests(
            java.lang.Iterable<? extends com.flipkart.vbroker.proto.UnsidelineRequest> values) {
            if (unsidelineRequestsBuilder_ == null) {
                ensureUnsidelineRequestsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                    values, unsidelineRequests_);
                onChanged();
            } else {
                unsidelineRequestsBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
         */
        public Builder clearUnsidelineRequests() {
            if (unsidelineRequestsBuilder_ == null) {
                unsidelineRequests_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
            } else {
                unsidelineRequestsBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
         */
        public Builder removeUnsidelineRequests(int index) {
            if (unsidelineRequestsBuilder_ == null) {
                ensureUnsidelineRequestsIsMutable();
                unsidelineRequests_.remove(index);
                onChanged();
            } else {
                unsidelineRequestsBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
         */
        public com.flipkart.vbroker.proto.UnsidelineRequest.Builder getUnsidelineRequestsBuilder(
            int index) {
            return getUnsidelineRequestsFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
         */
        public com.flipkart.vbroker.proto.UnsidelineRequestOrBuilder getUnsidelineRequestsOrBuilder(
            int index) {
            if (unsidelineRequestsBuilder_ == null) {
                return unsidelineRequests_.get(index);
            } else {
                return unsidelineRequestsBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
         */
        public java.util.List<? extends com.flipkart.vbroker.proto.UnsidelineRequestOrBuilder>
        getUnsidelineRequestsOrBuilderList() {
            if (unsidelineRequestsBuilder_ != null) {
                return unsidelineRequestsBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(unsidelineRequests_);
            }
        }

        /**
         * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
         */
        public com.flipkart.vbroker.proto.UnsidelineRequest.Builder addUnsidelineRequestsBuilder() {
            return getUnsidelineRequestsFieldBuilder().addBuilder(
                com.flipkart.vbroker.proto.UnsidelineRequest.getDefaultInstance());
        }

        /**
         * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
         */
        public com.flipkart.vbroker.proto.UnsidelineRequest.Builder addUnsidelineRequestsBuilder(
            int index) {
            return getUnsidelineRequestsFieldBuilder().addBuilder(
                index, com.flipkart.vbroker.proto.UnsidelineRequest.getDefaultInstance());
        }

        /**
         * <code>repeated .proto.UnsidelineRequest unsidelineRequests = 1;</code>
         */
        public java.util.List<com.flipkart.vbroker.proto.UnsidelineRequest.Builder>
        getUnsidelineRequestsBuilderList() {
            return getUnsidelineRequestsFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.flipkart.vbroker.proto.UnsidelineRequest, com.flipkart.vbroker.proto.UnsidelineRequest.Builder, com.flipkart.vbroker.proto.UnsidelineRequestOrBuilder>
        getUnsidelineRequestsFieldBuilder() {
            if (unsidelineRequestsBuilder_ == null) {
                unsidelineRequestsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                    com.flipkart.vbroker.proto.UnsidelineRequest, com.flipkart.vbroker.proto.UnsidelineRequest.Builder, com.flipkart.vbroker.proto.UnsidelineRequestOrBuilder>(
                    unsidelineRequests_,
                    ((bitField0_ & 0x00000001) == 0x00000001),
                    getParentForChildren(),
                    isClean());
                unsidelineRequests_ = null;
            }
            return unsidelineRequestsBuilder_;
        }

        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:proto.UnsidelineRequests)
    }

}

