// automatically generated by the FlatBuffers compiler, do not modify

package com.flipkart.vbroker.flatbuf;

public final class HttpMethod {
    public static final int POST = 0;
    public static final int PUT = 1;
    public static final int DELETE = 2;
    public static final int PATCH = 3;
    public static final String[] names = {"POST", "PUT", "DELETE", "PATCH",};

    private HttpMethod() {
    }

    public static String name(int e) {
        return names[e];
    }
}

