@startuml
start

if () then (Buffer Usage < 70%)
    :Produce to L2;
    stop
else (Buffer Usage > 70%)
    if () then (Buffer Usage < 90%)
        :Start donwgrade stream;
        note left
           Downgrade stream
           is essentially a subscription
           that "consumes" messages by
           dumping to L3.

           It starts consuming from the lowest
           unconsumed offset in a group among all
           subscriber offsets.

           Potentially it can skip some
           groups if the offsets for them
           are almost caught up.

        end note
        :Switch slow subscriptions to L3;
        :Produce to L2;
        stop
    else (Buffer Usage > 90%)
        :Block producing;
                note right
                    This happens only
                    when the producing rate is
                    faster than the rate at which
                    we can dump messages to disk
                end note

        :Wait until downgrade stream catches up;
        :Unblock producing;
        :Produce to L2;
        stop
endif
@enduml