@startuml
title L1 message flow
Producer -> SocketIn : Accept message
box "VBroker" #LightBlue
    participant SocketIn
    participant KPipe
    participant SubscriberPipe
    participant UserSpace
    participant SocketOut
end box
SocketIn -> UserSpace : Read metadata to user space
SocketIn -> KPipe : Splice Data
KPipe -> SubscriberPipe : Tee Data
SubscriberPipe -> SocketOut : Splice Request Payload
SocketOut -> Destination : HTTP Call
Destination -> SocketOut : HTTP Response
SocketOut -> UserSpace : Read metadata to user space
SocketOut -> SocketIn : Splice Response Payload
SocketIn -> Producer : Forward HTTP Response
@enduml