// automatically generated by the FlatBuffers compiler, do not modify

package com.flipkart.vbroker.entities;

public final class SubscriptionMechanism {
  private SubscriptionMechanism() { }
  public static final byte PUSH = 0;
  public static final byte PULL = 1;

  public static final String[] names = { "PUSH", "PULL", };

  public static String name(int e) { return names[e]; }
}

