// automatically generated by the FlatBuffers compiler, do not modify

package com.flipkart.vbroker.entities;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GetQueueRequest extends Table {
    public static GetQueueRequest getRootAsGetQueueRequest(ByteBuffer _bb) {
        return getRootAsGetQueueRequest(_bb, new GetQueueRequest());
    }

    public static GetQueueRequest getRootAsGetQueueRequest(ByteBuffer _bb, GetQueueRequest obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public static int createGetQueueRequest(FlatBufferBuilder builder,
                                            short queueId) {
        builder.startObject(1);
        GetQueueRequest.addQueueId(builder, queueId);
        return GetQueueRequest.endGetQueueRequest(builder);
    }

    public static void startGetQueueRequest(FlatBufferBuilder builder) {
        builder.startObject(1);
    }

    public static void addQueueId(FlatBufferBuilder builder, short queueId) {
        builder.addShort(0, queueId, 0);
    }

    public static int endGetQueueRequest(FlatBufferBuilder builder) {
        int o = builder.endObject();
        return o;
    }

    public void __init(int _i, ByteBuffer _bb) {
        bb_pos = _i;
        bb = _bb;
    }

    public GetQueueRequest __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public short queueId() {
        int o = __offset(4);
        return o != 0 ? bb.getShort(o + bb_pos) : 0;
    }
}

