// automatically generated by the FlatBuffers compiler, do not modify

package com.flipkart.vbroker.entities;

public final class ResponseMessage {
    public static final byte NONE = 0;
    public static final byte ProduceResponse = 1;
    public static final String[] names = {"NONE", "ProduceResponse",};

    private ResponseMessage() {
    }

    public static String name(int e) {
        return names[e];
    }
}

