// automatically generated by the FlatBuffers compiler, do not modify

package com.flipkart.vbroker.entities;

public final class StatusCode {
    public static final short ProduceSuccess_NoError = 101;
    public static final short ProduceFailed_NoLeader = 151;
    public static final short ProduceFailed_NotEnoughReplicas = 152;
    public static final short ConsumeSuccess_NoError = 201;
    public static final short ConsumeError_DestinationDown = 251;
    private StatusCode() {
    }
}

